# Generated by Django 6.0.5 on 2026-06-09 12:21

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0032_make_procedures_managed"),
        ("pghistory", "0007_auto_20250421_0444"),
        ("users", "0003_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="Change",
            fields=[],
            options={
                "verbose_name": "Changement",
                "verbose_name_plural": "Changements",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("pghistory.events",),
            managers=[
                ("no_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EventSnapshot",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("type", models.TextField(blank=True, null=True)),
                ("code", models.TextField(blank=True, null=True)),
                (
                    "date_evenement",
                    models.DateField(
                        db_column="date_iso", null=True, verbose_name="date"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "from_sudocuh",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="from_sudocuh"
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="procedure_type_code_date_evenement_description_profile_from_sudocuh_events",
                        to="core.event",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="core.procedure",
                        verbose_name="procédure",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="users.profile",
                        verbose_name="profil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instantané de l'évènement",
                "verbose_name_plural": "Instantanés de l'évènement",
                "abstract": False,
            },
        ),
    ]
