# Generated by Django 6.0.5 on 2026-06-09 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            WITH events AS (
                select
                    event.id,
                    event.code,
                    event.date_iso,
                    event.description,
                    event.from_sudocuh,
                    event.procedure_id,
                    event.profile_id,
                    event.type
                FROM doc_frise_events as event
            )
            INSERT INTO "history_eventsnapshot"
                ("code", "date_iso", "description", "from_sudocuh", "procedure_id", "profile_id", "type",
                "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id")
            select "code", "date_iso", "description", "from_sudocuh", "procedure_id", "profile_id", "type",
              _pgh_attach_context(), NOW(), 'insert', events."id"
            from events;
            """,
            reverse_sql="""
                TRUNCATE "history_eventsnapshot";
            """,
        )
    ]
