# Generated by Django 6.0.6 on 2026-06-16 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0002_events_initial_snapshots"),
        ("users", "0003_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsnapshot",
            name="date_evenement",
            field=models.DateField(
                blank=True, db_column="date_iso", null=True, verbose_name="date"
            ),
        ),
        migrations.AlterField(
            model_name="eventsnapshot",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="users.profile",
                verbose_name="profil",
            ),
        ),
    ]
