# Generated by Django 6.0.6 on 2026-06-16 13:38

from django.db import migrations


def enable_rls(table_name: str) -> str:
    return f'alter table "{table_name}" enable row level security;'


def disable_rls(table_name: str) -> str:
    return f'alter table "{table_name}" disable row level security;'


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0003_alter_eventsnapshot_date_evenement_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=enable_rls(table_name="history_eventsnapshot"),
            reverse_sql=disable_rls(table_name="history_eventsnapshot"),
        ),
        migrations.RunSQL(
            sql=enable_rls(table_name="pghistory_context"),
            reverse_sql=disable_rls(table_name="pghistory_context"),
        ),
    ]
