# Generated by Django 6.0.6 on 2026-06-16 13:38

from django.db import migrations


def drop_policy(policy_name: str, table_name: str) -> str:
    return f"drop policy if exists {policy_name} on {table_name}"


VERIFIED_USER_CAN_INSERT_SQL = """
    CREATE POLICY "verified_users_can_insert" ON public.history_eventsnapshot FOR INSERT WITH CHECK ((
    SELECT profiles.verified
        FROM public.profiles
        WHERE (auth.uid() = profiles.user_id)
    ));
"""


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0004_historyeventsnapshot_rls"),
    ]

    operations = [
        migrations.RunSQL(
            sql=VERIFIED_USER_CAN_INSERT_SQL,
            reverse_sql=drop_policy(
                "verified_users_can_insert",
                "public.history_eventsnapshot",
            ),
        ),
    ]
