# Generated by Django 6.0.6 on 2026-07-16 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0005_eventsnapshot_add_insert_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsnapshot",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="snapshots",
                related_query_name="snapshots_qs",
                to="core.event",
            ),
        ),
    ]
