# Generated by Django 6.0.7 on 2026-07-20 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_event_add_event_type"),
        ("history", "0006_alter_eventsnapshot_pgh_obj"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsnapshot",
            name="event_type",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="core.eventtype",
                verbose_name="type",
            ),
        ),
    ]
