# Generated by Django 6.0.7 on 2026-07-21 15:16

import django.db.models.deletion
from django.db import migrations, models


def delete_eventsnapshots_without_procedure(apps, schema_editor) -> None:  # noqa: ANN001, ARG001
    EventSnapshot = apps.get_model("history", "EventSnapshot")
    EventSnapshot.objects.filter(procedure__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_alter_event_procedure"),
        ("history", "0007_event_add_event_type"),
    ]

    operations = [
        migrations.RunPython(
            delete_eventsnapshots_without_procedure,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.AlterField(
            model_name="eventsnapshot",
            name="procedure",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="core.procedure",
                verbose_name="procédure",
            ),
        ),
    ]
