# Generated by Django 6.0.7 on 2026-07-30 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_alter_event_event_type_blank"),
        ("history", "0008_alter_eventsnapshot_procedure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsnapshot",
            name="event_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="core.eventtype",
                verbose_name="type",
            ),
        ),
    ]
