# This Dockerfile is only used by Dependabot to keep tracks of Metabase version upgrades
FROM metabase/metabase:v0.63.18.5

LABEL org.opencontainers.image.source="https://github.com/metabase/metabase"
