[tools]
node = "20"

[tasks."start:nuxt"]
dir = "{{config_root}}/nuxt"
run = "npm run dev"

[tasks."start:django"]
dir = "{{config_root}}/django"
run = "./manage.py runserver"

[tasks."start:supabase"]
description="""
Serveur local Supabase.
"""
dir = "{{config_root}}"
run = "supabase start"

[tasks.start]
depends = ["start:nuxt", "start:django", "start:supabase"]

[tasks."database:restore"]
description="""
Restauration locale de la dernière sauvegarde.
L'URL de la base de données n'est pas passée en paramètre pour éviter tout risque.
"""
depends = ["start:supabase"]
dir = "{{config_root}}/django"
run = "/usr/bin/bash scripts/restore_database.sh postgresql://postgres:postgres@127.0.0.1:54322/postgres"

[tasks."rclone:move_exports_to_outscale"]
description ="""
Copy files located in the /exports directory to the remote S3 directory and delete them locally.
To only copy files without deleting them, use `rclone copy`.
"""
dir = "{{config_root}}/django"
run = "rclone --config scripts/rclone.conf move --s3-chunk-size=20M exports/ docurba_exports:/docurba-exports"

[tasks."rclone:copy_exports_from_outscale"]
dir = "{{config_root}}/django"
run = "rclone --config scripts/rclone.conf copy --s3-chunk-size=20M docurba_exports:/docurba-exports exports/"

[tasks."rclone:move_exports_from_outscale"]
dir = "{{config_root}}/django"
run = "rclone --config scripts/rclone.conf copy --s3-chunk-size=20M docurba_exports:/docurba-exports exports/"

