[tools]
node = "20"
python = "3.13"
uv = 'latest'
supabase = 'latest'

[env]
_.python.venv = "{{config_root}}/django/.venv"
NUXT3_PATH= { required = true }

[settings]
python.uv_venv_auto = "create|source"

[tasks."start:nuxt"]
dir = "{{config_root}}/nuxt"
run = "npm run dev"

[tasks."start:nuxt3"]
description="""
Serveur local Nuxt3.
Attention, le dépôt doit avoir été cloné et Mise doit avoir été installé avant.
Ensuite, assignez $NUXT3_PATH au chemin vers le dépôt.
"""
dir = "{{env.NUXT3_PATH}}"
run = "mise start"

[tasks."start:django"]
dir = "{{config_root}}/django"
run = "./manage.py runserver"

[tasks."start:supabase"]
description="""
Serveur local Supabase contenant une interface web (Supabase studio), une base de données, un serveur SSO et un S3.
"""
dir = "{{config_root}}"
run = "supabase start"

[tasks."start:tests"]
description="""
Serveur PG initialisé avec le schéma de production et les migrations Django.
"""
dir = "{{config_root}}"
run = '''
    #!/bin/bash
    docker compose up test_db -d
    RETRIES=15
    until docker compose exec test_db bash -c '(psql -c "select 1 from public.only_exists_in_test;") > /dev/null 2>&1' || [ ${RETRIES} -eq 0 ]; do
        echo "Waiting for Postgres server, $((RETRIES--)) remaining attempts..."
        sleep 2
    done
    DJANGO_SETTINGS_MODULE=config.settings.test django-admin migrate
'''

[tasks."start"]
depends = ["start:nuxt", "start:django", "start:supabase", "start:nuxt3", "start:tests"]

[tasks."database:restore"]
description="""
Restauration locale de la dernière sauvegarde.
L'URL de la base de données n'est pas passée en paramètre pour éviter tout risque.
Il s'agit de l'URL du serveur local Supabase (lancé avec `supabase start` ou `mise start:supabase`).
"""
depends = ["start:supabase"]
dir = "{{config_root}}/django"
run = "/usr/bin/bash scripts/restore_database.sh postgresql://postgres:postgres@127.0.0.1:54322/postgres"

[tasks."rclone:move_exports_to_outscale"]
description ="""
Copy files located in the /exports directory to the remote S3 directory and delete them locally.
To only copy files without deleting them, use `rclone copy`.
"""
dir = "{{config_root}}/django"
run = "rclone --config scripts/rclone.conf move --s3-chunk-size=20M exports/ docurba_exports:/docurba-exports"

[tasks."rclone:copy_exports_from_outscale"]
dir = "{{config_root}}/django"
run = "rclone --config scripts/rclone.conf copy --s3-chunk-size=20M docurba_exports:/docurba-exports exports/"

[tasks."rclone:move_exports_from_outscale"]
dir = "{{config_root}}/django"
run = "rclone --config scripts/rclone.conf copy --s3-chunk-size=20M docurba_exports:/docurba-exports exports/"

[tasks."install_deps:django"]
description="Install django dependencies"
dir = "{{config_root}}/django"
run = "mise exec -- uv sync"

[tasks."install_deps:nuxt"]
description="Install nuxt dependencies"
dir = "{{config_root}}/nuxt"
run = "mise exec -- npm install ."

[tasks."install_deps:nuxt3"]
description="Install nuxt3 dependencies"
dir = "{{env.NUXT3_PATH}}"
run = "mise exec -- npm install ."

[tasks."install_deps"]
description="Install all projects dependencies"
depends = ["install_deps:nuxt", "install_deps:django", "install_deps:nuxt3"]

[tasks."clean_deps:django"]
description="Clean django dependencies"
dir = "{{config_root}}/django"
run = "rm -Rf .venv"

[tasks."clean_deps:nuxt"]
description="Clean nuxt dependencies"
dir = "{{config_root}}/nuxt"
run = "rm -Rf nodes_modules"

[tasks."clean_deps:nuxt3"]
description="Clean nuxt3 dependencies"
dir = "{{env.NUXT3_PATH}}"
run = "rm -Rf nodes_modules"

[tasks."clean"]
description="Clean all projects dependencies"
depends = ["clean_deps:nuxt", "clean_deps:django", "clean_deps:nuxt3"]
run = "mise uninstall --all"