DROP TABLE IF EXISTS public.sudocu_procedures_infosdgd;
CREATE TABLE public.sudocu_procedures_infosdgd AS
  SELECT procedure.noserieprocedure as procedure_id,
  voletqualitatif.noserievoletqualitatif as vq_noserievoletqualitatif,
  voletqualitatif.sievaluationenvironement as vq_sievaluationenvironement,
  voletqualitatif.sidocammenagmentcomm as vq_sidocammenagmentcomm,
  voletqualitatif.siintegrationdispoloiene as vq_siintegrationdispoloiene,
  voletqualitatif.sievaluationenvironnementale as vq_sievaluationenvironnementale,
  voletqualitatif.siscotavecdac as vq_siscotavecdac,
  voletqualitatif.siloilme as vq_siloilme,
  voletqualitatif.siloiene as vq_siloiene,
  voletqualitatif.siespacenaturels as vq_siespacenaturels,
  voletqualitatif.siespaceagricoles as vq_siespaceagricoles,
  voletqualitatif.siespaceurbains as vq_siespaceurbains,
  voletqualitatif.sischemassecteur as vq_sischemassecteur,
  voletqualitatif.sichapitrevalantsmvm as vq_sichapitrevalantsmvm,
  voletqualitatif.sicompatibilitelittoral as vq_sicompatibilitelittoral,
  voletqualitatif.sicompatibilitemontagne as vq_sicompatibilitemontagne,
  voletqualitatif.sicompatibilitesdage as vq_sicompatibilitesdage,
  voletqualitatif.sicompatibilitepgri as vq_sicompatibilitepgri,
  voletqualitatif.sicompatibiliteparcsnaturels as vq_sicompatibiliteparcsnaturels,
  voletqualitatif.sipriseencptsrce as vq_sipriseencptsrce,
  voletqualitatif.sipriseencptpcet as vq_sipriseencptpcet,
  loiene.noserieloiene as le_noserieloiene,
  loiene.sinbrmaxairestationnement as le_sinbrmaxairestationnement,
  loiene.siplansecteur as le_siplansecteur,
  loiene.sidensitemin as le_sidensitemin,
  loiene.sisecteurprojet as le_sisecteurprojet,
  loiene.sienvironnement as le_sienvironnement,
  loiene.sipaysage as le_sipaysage,
  loiene.sientreeville as le_sientreeville,
  loiene.sipatrimoine as le_sipatrimoine,
  loiene.silutteinsalubrite as le_silutteinsalubrite,
  loiene.sirenouvellementurbain as le_sirenouvellementurbain,
  loiene.sideveloppement as le_sideveloppement,
  loiene.siecheancierouvertureurba as le_siecheancierouvertureurba,
  loiene.sischemasamenagements as le_sischemasamenagements,
  loiene.sizonesnaturelles as le_sizonesnaturelles,
  loiene.sizonesagricoles as le_sizonesagricoles,
  loiene.siprescriptions as le_siprescriptions,
  loiene.siobjconsoespaceparsecteur as le_siobjconsoespaceparsecteur,
  loiene.siutilisationterrainavanturba as le_siutilisationterrainavanturba,
  loiene.sietudeimpacteurbanisation as le_sietudeimpacteurbanisation,
  loiene.sietudedensification as le_sietudedensification,
  loiene.sisecteurdensitemin as le_sisecteurdensitemin,
  loiene.siobligationstationnement as le_siobligationstationnement,
  loiene.siobligationplustationnement as le_siobligationplustationnement,
  loiene.sisecteurenergieenvironnement as le_sisecteurenergieenvironnement,
  loiene.sisecteurcommunicationelectro as le_sisecteurcommunicationelectro,
  loiene.sisecteuravecnorme as le_sisecteuravecnorme,
  loiene.siespacevert as le_siespacevert,
  loiene.simodaliterepartitionlogementepci as le_simodaliterepartitionlogementepci,
  loiene.simodaliterepartitionlogementcommune as le_simodaliterepartitionlogementcommune,
  loiene.siobjectifameliorationparc as le_siobjectifameliorationparc,
  loiene.sipublicationanalyse as le_sipublicationanalyse,
  loiene.datevoletqualitatif as le_datevoletqualitatif,
  loiene.commentaire as le_commentaire,
  dgd.noseriedgd as dgd_noseriedgd,
  dgd.anneedgd as dgd_anneedgd,
  dgd.categoriedgd as dgd_categoriedgd,
  dgd.montantdgd as dgd_montantdgd,
  dgd.commentaire as dgd_commentaire
  FROM sudocu.procedure as procedure
  LEFT JOIN sudocu.voletqualitatif voletqualitatif ON procedure.noserieprocedure = voletqualitatif.noserieprocedure
  LEFT JOIN sudocu.loiene loiene ON procedure.noserieprocedure = loiene.noserieprocedure
  LEFT JOIN sudocu.dgd dgd ON procedure.noserieprocedure = dgd.noserieprocedure;
