# Generated by Django 5.1.5 on 2025-04-24 09:44
# ruff: noqa: RUF012
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collectivite",
            old_name="code_insee",
            new_name="code_insee_unique",
        ),
    ]
