# Generated by Django 5.1.5 on 2025-07-30 09:48
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_viewcommuneadhesionsdeep"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="commune",
            index=models.Index(
                condition=models.Q(("nouvelle__isnull", True)),
                fields=["collectivite_ptr"],
                name="collectivite_nouvelle_null_idx",
                opclasses=["varchar_pattern_ops"],
            ),
        ),
    ]
