# Generated by Django 5.1.5 on 2025-09-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_viewcollectiviteadhesionsdeep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False, 'ordering': ('-date_evenement',)},
        ),
    ]
