# Generated by Django 5.1.5 on 2025-08-24 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_viewcollectiviteadhesionsdeep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False, 'ordering': ('-date_evenement',)},
        ),
        migrations.RenameField(
            model_name='collectivite',
            old_name='id',
            new_name='code_type',
        ),
    ]
