# ruff: noqa: RUF012
# Generated by Django 5.2.10 on 2026-01-27 10:22

from django.db import migrations

# nuxt/sql/rpc/validated_collectivites_by_depts.sql
VALIDATED_COLLECTIVITES_FUNCTION = """
CREATE OR REPLACE FUNCTION validated_collectivites(since date, departement text)
RETURNS TABLE (
    collectivite_code text,
    created_at timestamp,
    profile_id uuid,
    email text
)
LANGUAGE sql
AS $$
SELECT
	inn.*,
	pf.email
FROM
	(
		SELECT
			pv.collectivite_code,
			MIN(pv.created_at) AS created_at,
			MIN(pv.profile_id::text)::UUID AS profile_id
		FROM
			procedures_validations pv
		WHERE
			pv.created_at > since
			AND pv.departement = departement
		GROUP BY
			pv.collectivite_code
		ORDER BY
			pv.collectivite_code
	) AS inn
	LEFT JOIN profiles pf ON inn.profile_id = pf.user_id;
$$;
"""

VALIDATED_COLLECTIVITES_2024_FUNCTION = """
CREATE OR REPLACE FUNCTION validated_collectivites_2024(department_param text)
RETURNS TABLE (
    collectivite_code text,
    created_at timestamp,
    profile_id uuid,
    email text
)
LANGUAGE sql
AS $$
SELECT inn.*, email
FROM (
    SELECT DISTINCT pv.collectivite_code,
    MIN(pv.created_at) as created_at,
    MIN(pv.profile_id::text)::uuid as profile_id
    FROM procedures_validations pv
    WHERE pv.created_at > '2024-06-01'
    AND pv.departement = department_param
    GROUP BY pv.collectivite_code, pv.procedure_id
    ORDER BY pv.collectivite_code
    ) as inn
    left join profiles pf on inn.profile_id = pf.user_id;
$$;
"""

# nuxt/sql/rpc/validated_collectivites.sql
VALIDATED_COLLECTIVITES_BY_DEPT_FUNCTION = """
CREATE OR REPLACE FUNCTION validated_collectivites_by_depts(since date)
RETURNS TABLE (
    departement text,
    unique_collectivites_count bigint
)
LANGUAGE sql
SECURITY DEFINER
AS $$
SELECT
	departement,
	COUNT(DISTINCT collectivite_code) AS unique_collectivites_count
FROM
	procedures_validations
WHERE
  created_at > since
GROUP BY
	departement
ORDER BY
	departement;
$$;
"""

VALIDATED_COLLECTIVITES_BY_DEPT_2024_FUNCTION = """
CREATE OR REPLACE FUNCTION validated_collectivites_by_depts_2024()
RETURNS TABLE (
    departement text,
    unique_collectivites_count bigint
)
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT
        departement,
        COUNT(DISTINCT collectivite_code) as unique_collectivites_count
    FROM
        procedures_validations
    WHERE
        departement IS NOT NULL
        AND created_at >= '2024-06-01'
    GROUP BY
        departement
    ORDER BY
        departement;
$$;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_event_options"),
    ]

    operations = [
        migrations.RunSQL(
            sql=VALIDATED_COLLECTIVITES_FUNCTION,
            reverse_sql=VALIDATED_COLLECTIVITES_2024_FUNCTION,
        ),
        migrations.RunSQL(
            sql=VALIDATED_COLLECTIVITES_BY_DEPT_FUNCTION,
            reverse_sql=VALIDATED_COLLECTIVITES_BY_DEPT_2024_FUNCTION,
        ),
    ]
