# Generated by Django 5.1.5 on 2025-12-01 09:49
# ruff: noqa: RUF012

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_event_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commune",
            name="intercommunalite",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.collectivite",
            ),
        ),
    ]
