# Generated by Django 5.1.5 on 2025-08-24 01:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_event_options_rename_id_collectivite_code_type"),
    ]

    operations = [
        migrations.DeleteModel("Commune"),
        migrations.DeleteModel("Collectivite"),
        migrations.DeleteModel("Departement"),
        migrations.DeleteModel("Region"),
    ]
