# Generated by Django 5.2.10 on 2026-02-05 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_event_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="communeprocedure",
            options={"managed": False, "verbose_name": "Périmètre"},
        ),
    ]
