# Generated by Django 5.2.10 on 2026-02-09 22:40

import django.contrib.postgres.fields
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_communeprocedure_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("archived", models.BooleanField(db_default=False)),
                (
                    "current_perimetre",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(blank=True, null=True),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "initial_perimetre",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(blank=True, null=True),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("current_perimetre_new", models.JSONField(blank=True, null=True)),
                ("doc_type", models.CharField()),
                ("doc_type_code", models.TextField(blank=True, null=True)),
                ("epci", models.JSONField(blank=True, null=True)),
                (
                    "from_sudocuh",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "from_sudocuh_procedure_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("is_sudocuh_scot", models.BooleanField(blank=True, null=True)),
                ("name", models.CharField(blank=True, null=True)),
                ("pac", models.JSONField(blank=True, db_column="PAC", null=True)),
                ("region", models.CharField(blank=True, null=True)),
                ("sudocuh_procedure_id", models.IntegerField(blank=True, null=True)),
                ("test", models.BooleanField(blank=True, null=True)),
                ("towns", models.JSONField(blank=True, null=True)),
                ("trame", models.CharField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "projet",
                "db_table": "projects",
                "managed": False,
            },
        ),
    ]
