# Generated by Django 6.0.2 on 2026-02-27 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_communeprocedure_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "base_manager_name": "objects",
                "managed": False,
                "ordering": ("-date_evenement",),
            },
        ),
    ]
