# Generated by Django 6.0.2 on 2026-03-01 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_communeprocedure_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commune",
            name="intercommunalite",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.collectivite",
            ),
        ),
    ]
