# Generated by Django 5.1.5 on 2025-08-24 22:42
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_departement_region_collectivite_departement_region_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="commune",
            name="collectivite_nouvelle_null_idx",
        ),
        # migrations.RemoveField(
        #     model_name="commune",
        #     name="code_type_copie",
        # ),
        migrations.AddIndex(
            model_name="commune",
            index=models.Index(
                condition=models.Q(("nouvelle__isnull", True)),
                fields=["collectivite_ptr"],
                name="collectivite_nouvelle_null_idx",
            ),
        ),
    ]
