# Generated by Django 6.0.2 on 2026-02-27 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_project"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="procedure",
            options={"base_manager_name": "objects", "managed": False},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "base_manager_name": "objects",
                "managed": False,
                "verbose_name": "projet",
            },
        ),
    ]
