# ruff: noqa: RUF012
# Generated by Django 5.1.5 on 2025-12-12 09:41

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
            ],
            options={
                "db_table": '"auth"."users"',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.user",
                        verbose_name="Utilisateur",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                ("firstname", models.CharField(blank="True", verbose_name="Prénom")),
                ("lastname", models.CharField(blank="True", verbose_name="Nom")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "poste",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ddt", "DDT(M)/DEAL"),
                            ("dreal", "DREAL"),
                            ("be", "Bureau d'études"),
                            ("elu", "Collectivité, Élu·e"),
                            (
                                "employe_mairie",
                                "Collectivité, Technicien·ne ou employé·e",
                            ),
                            ("agence_urba", "Agence d'urbanisme"),
                            ("autre", "Autre"),
                        ],
                        verbose_name="Poste",
                    ),
                ),
                (
                    "other_poste",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                (
                                    "chef_unite",
                                    "Chef·fe d'unité/de bureau/de service et adjoint·e",
                                ),
                                ("redacteur_pac", "Rédacteur·ice de PAC"),
                                (
                                    "suivi_procedures",
                                    "Chargé·e de l'accompagnement des collectivités",
                                ),
                                ("referent_sudocuh", "Référent·e Sudocuh"),
                            ],
                        ),
                        blank=True,
                        size=10,
                        verbose_name="Role(s)",
                    ),
                ),
                (
                    "departement",
                    models.CharField(blank=True, verbose_name="Département"),
                ),
                ("tel", models.CharField(blank=True, verbose_name="Téléphone")),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                (
                    "side",
                    models.CharField(
                        blank=True,
                        choices=[("etat", "État"), ("collectivite", "Collectivité")],
                        verbose_name="Type",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        db_comment="Si l'utilisateur est une DREAL, son scope est une région. Cette peut être vide si c'est un autre poste que DREAL.",
                        verbose_name="Région",
                    ),
                ),
                (
                    "no_signup",
                    models.BooleanField(
                        db_comment="Si l'utilisateur passe par un depot d'acte, il est authrosié de mettre uniquement son email. Dans ce cas l'utilisateur n'a pas de compte Docurba, et no_signup sera à TRUE. ",
                        default=False,
                        verbose_name="Dépôt d'actes",
                    ),
                ),
                (
                    "successfully_logged_once",
                    models.BooleanField(default=False, verbose_name="Déjà connecté"),
                ),
                (
                    "optin",
                    models.BooleanField(
                        default=False, verbose_name="Inscrit à l'infolettre"
                    ),
                ),
                (
                    "updated_pipedrive",
                    models.BooleanField(
                        default=False, verbose_name="Mis à jour Pipedrive"
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        db_comment="super admin bypass",
                        default=False,
                        verbose_name="Est admin",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Est membre"),
                ),
            ],
            options={
                "db_table": "profiles",
                "managed": False,
            },
        ),
    ]
