# ruff: noqa: RUF012
# Generated by Django 5.1.5 on 2026-01-08 13:44

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
            ],
            options={
                "verbose_name": "utilisateur",
                "managed": False,
                "db_table": '"auth"."users"',
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.user",
                        verbose_name="Utilisateur",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(blank=True, null=True, verbose_name="Prénom"),
                ),
                (
                    "lastname",
                    models.CharField(blank=True, null=True, verbose_name="Nom"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "poste",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ddt", "DDT(M)/DEAL"),
                            ("dreal", "DREAL"),
                            ("region", "Région"),
                            ("be", "Bureau d'études"),
                            ("elu", "Collectivité, Élu·e"),
                            (
                                "employe_mairie",
                                "Collectivité, Technicien·ne ou employé·e",
                            ),
                            ("agence_urba", "Agence d'urbanisme"),
                            ("autre", "Autre"),
                        ],
                        null=True,
                        verbose_name="Poste",
                    ),
                ),
                (
                    "other_poste",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                (
                                    "chef_unite",
                                    "Chef·fe d'unité/de bureau/de service et adjoint·e",
                                ),
                                ("redacteur_pac", "Rédacteur·ice de PAC"),
                                (
                                    "suivi_procedures",
                                    "Chargé·e de l'accompagnement des collectivités",
                                ),
                                ("referent_sudocuh", "Référent·e Sudocuh"),
                            ],
                        ),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Role(s)",
                    ),
                ),
                (
                    "departement",
                    models.CharField(blank=True, null=True, verbose_name="Département"),
                ),
                (
                    "collectivite_id",
                    models.CharField(
                        blank=True, null=True, verbose_name="Code Collectivité"
                    ),
                ),
                (
                    "tel",
                    models.CharField(blank=True, null=True, verbose_name="Téléphone"),
                ),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                (
                    "side",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("etat", "État"),
                            ("collectivite", "Collectivité"),
                            ("ppa", "PPA"),
                        ],
                        null=True,
                        verbose_name="Side",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        db_comment="Si l'utilisateur est une DREAL ou une PPA : région de son périmètre. La colonne peut être remplie pour les autres types.",
                        null=True,
                        verbose_name="Région",
                    ),
                ),
                (
                    "no_signup",
                    models.BooleanField(
                        db_comment="Si l'utilisateur passe par un depot d'acte, il est autorisé à mettre uniquement son email. Dans ce cas l'utilisateur n'a pas de compte Docurba, et no_signup sera à TRUE.",
                        default=False,
                        verbose_name="Dépôt d'actes (no_signup)",
                    ),
                ),
                (
                    "successfully_logged_once",
                    models.BooleanField(
                        default=False, verbose_name="S'est déjà connecté"
                    ),
                ),
                (
                    "optin",
                    models.BooleanField(
                        default=False, verbose_name="Est inscrit à l'infolettre"
                    ),
                ),
                (
                    "updated_pipedrive",
                    models.BooleanField(
                        default=False, verbose_name="Est mis à jour sur Pipedrive"
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        db_comment="super admin bypass",
                        default=False,
                        verbose_name="Est admin (is_admin)",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, verbose_name="Est membre (is_staff)"
                    ),
                ),
            ],
            options={
                "verbose_name": "profil",
                "db_table": "profiles",
                "managed": False,
            },
        ),
    ]
