# ruff: noqa: RUF012
# Generated by Django 5.1.5 on 2025-12-03 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[("ALTER TABLE public.profiles ADD COLUMN departements text[]")],
            reverse_sql=[("ALTER TABLE public.profiles DROP COLUMN departements")],
        )
    ]
