# Generated by Django 5.1.5 on 2025-04-13 13:02

from pathlib import Path

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models

import docurba.core.utils


def read_sql_from_file(filepath: str) -> str:
    p = Path(settings.APPS_DIR / "core" / "migrations" / "sql_statements" / filepath)
    return p.read_text()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=read_sql_from_file("create_table_projects.sql"),
                    reverse_sql=read_sql_from_file("drop_table_projects.sql"),
                ),
                migrations.RunSQL(
                    sql=read_sql_from_file("create_table_procedures.sql"),
                    reverse_sql=read_sql_from_file("drop_table_procedures.sql"),
                ),
                migrations.RunSQL(
                    sql=read_sql_from_file("create_table_procedures_perimetres.sql"),
                    reverse_sql=read_sql_from_file(
                        "drop_table_procedures_perimetres.sql"
                    ),
                ),
                migrations.RunSQL(
                    sql=read_sql_from_file("create_table_doc_frise_events.sql"),
                    reverse_sql=read_sql_from_file("drop_table_doc_frise_events.sql"),
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="Project",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                db_default=django.contrib.postgres.functions.RandomUUID(),
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                db_default=django.db.models.functions.datetime.Now()
                            ),
                        ),
                        ("archived", models.BooleanField(db_default=False)),
                        ("name", models.CharField(blank=True, null=True)),
                        ("test", models.BooleanField(blank=True, null=True)),
                        ("epci", models.JSONField(blank=True, null=True)),
                        (
                            "current_perimetre",
                            django.contrib.postgres.fields.ArrayField(
                                base_field=models.JSONField(blank=True, null=True),
                                blank=True,
                                null=True,
                            ),
                        ),
                        (
                            "initial_perimetre",
                            django.contrib.postgres.fields.ArrayField(
                                base_field=models.JSONField(blank=True, null=True),
                                blank=True,
                                null=True,
                            ),
                        ),
                        (
                            "current_perimetre_new",
                            models.JSONField(blank=True, null=True),
                        ),
                        ("doc_type", models.CharField()),
                        ("doc_type_code", models.TextField(blank=True, null=True)),
                        (
                            "from_sudocuh",
                            models.IntegerField(blank=True, null=True, unique=True),
                        ),
                        (
                            "from_sudocuh_procedure_id",
                            models.IntegerField(blank=True, null=True, unique=True),
                        ),
                        (
                            "sudocuh_procedure_id",
                            models.IntegerField(blank=True, null=True),
                        ),
                        ("is_sudocuh_scot", models.BooleanField(blank=True, null=True)),
                        (
                            "pac",
                            models.JSONField(blank=True, db_column="PAC", null=True),
                        ),
                        ("trame", models.CharField(blank=True, null=True)),
                        ("region", models.CharField(blank=True, null=True)),
                        ("towns", models.JSONField(blank=True, null=True)),
                        (
                            "collectivite",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                related_name="projects",
                                to="core.collectivite",
                                to_field="code_insee_unique",
                            ),
                        ),
                        (
                            "collectivite_porteuse",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                related_name="owned_projects",
                                to="core.collectivite",
                                to_field="code_insee_unique",
                            ),
                        ),
                        (
                            "owner",
                            models.ForeignKey(
                                blank=True,
                                db_column="owner",
                                null=True,
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                to="users.profile",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "projet",
                        "db_table": "projects",
                        "base_manager_name": "objects",
                    },
                ),
                migrations.CreateModel(
                    name="CommuneProcedure",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "procedures_perimetres",
                        "managed": False,
                    },
                ),
                migrations.CreateModel(
                    name="Event",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                db_default=django.contrib.postgres.functions.RandomUUID(),
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "from_sudocuh",
                            models.IntegerField(
                                blank=True,
                                null=True,
                                unique=True,
                                verbose_name="from_sudocuh",
                            ),
                        ),
                        ("type", models.TextField(blank=True, null=True)),
                        (
                            "date_evenement_string",
                            models.CharField(
                                db_column="date_iso", null=True, verbose_name="date"
                            ),
                        ),
                        (
                            "is_valid",
                            models.BooleanField(
                                db_default=True, verbose_name="est valide"
                            ),
                        ),
                        (
                            "profile",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.DO_NOTHING,
                                to="users.Profile",
                                verbose_name="profil",
                            ),
                        ),
                        (
                            "actors",
                            models.JSONField(
                                blank=True, null=True, verbose_name="acteurs"
                            ),
                        ),
                        (
                            "attachements",
                            models.JSONField(
                                blank=True, null=True, verbose_name="pièces-jointes"
                            ),
                        ),
                        (
                            "code",
                            models.TextField(blank=True, null=True),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                blank=True,
                                db_default=django.contrib.postgres.functions.TransactionNow(),
                                null=True,
                                verbose_name="créé le",
                            ),
                        ),
                        (
                            "description",
                            models.TextField(blank=True, null=True),
                        ),
                        (
                            "from_sudocuh_procedure_id",
                            models.IntegerField(
                                blank=True,
                                null=True,
                                verbose_name="from_sudocuh_procedure_id",
                            ),
                        ),
                        (
                            "is_sudocuh_scot",
                            models.BooleanField(
                                blank=True, null=True, verbose_name="is_sudocuh_scot"
                            ),
                        ),
                        (
                            "procedure",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                to="core.procedure",
                                verbose_name="procédure",
                            ),
                        ),
                        (
                            "project",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="core.project",
                            ),
                        ),
                        (
                            "test",
                            models.BooleanField(blank=True, null=True),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(
                                blank=True,
                                db_default=django.contrib.postgres.functions.TransactionNow(),
                                null=True,
                                verbose_name="modifié le",
                            ),
                        ),
                        (
                            "visibility",
                            models.TextField(
                                blank=True,
                                choices=[
                                    (
                                        "public",
                                        "Publique - Visible par le grand public",
                                    ),
                                    (
                                        "private",
                                        "Privé - Visible uniquement par les collaborateur·ices de la procédure",
                                    ),
                                ],
                                db_default="public",
                                null=True,
                                verbose_name="visibilité",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "doc_frise_events",
                        "ordering": ("-date_evenement_string",),
                        "managed": False,
                    },
                ),
                migrations.CreateModel(
                    name="Procedure",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                db_default=django.contrib.postgres.functions.RandomUUID(),
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "from_sudocuh",
                            models.IntegerField(blank=True, null=True, unique=True),
                        ),
                        (
                            "doc_type",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("CC", "Cc"),
                                    ("SCOT", "Scot"),
                                    ("SD", "Sd"),
                                    ("PLU", "Plu"),
                                    ("POS", "Pos"),
                                    ("PLUi", "Plui"),
                                    ("PLUiH", "Pluih"),
                                    ("PLUiHM", "Pluihm"),
                                    ("PLUiM", "Pluim"),
                                ],
                                null=True,
                            ),
                        ),
                        ("name", models.TextField(blank=True, null=True)),
                        ("type", models.CharField(blank=True, null=True)),
                        ("numero", models.CharField(blank=True, null=True)),
                        (
                            "created_at",
                            models.DateTimeField(
                                db_default=django.contrib.postgres.functions.TransactionNow(),
                                null=True,
                            ),
                        ),
                        (
                            "last_updated_at",
                            models.DateTimeField(
                                db_default=django.contrib.postgres.functions.TransactionNow(),
                                null=True,
                            ),
                        ),
                        (
                            "soft_delete",
                            models.BooleanField(
                                db_default=False, verbose_name="archivée (soft_delete)"
                            ),
                        ),
                        (
                            "archived",
                            models.GeneratedField(
                                db_persist=True,
                                expression=models.Q(
                                    ("doublon_cache_de__isnull", False),
                                    ("soft_delete", True),
                                    _connector="OR",
                                ),
                                output_field=models.BooleanField(),
                                verbose_name="archivée (archived)",
                            ),
                        ),
                        (
                            "owner",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to="users.Profile",
                                verbose_name="propriétaire",
                                related_name="procedures",
                            ),
                        ),
                        (
                            "project",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="procedures",
                                to="core.project",
                                verbose_name="projet",
                            ),
                        ),
                        (
                            "collectivite_porteuse",
                            models.ForeignKey(
                                db_constraint=False,
                                null=True,
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                to="core.collectivite",
                                to_field="code_insee_unique",
                            ),
                        ),
                        (
                            "comment_dgd",
                            models.TextField(blank=True, null=True),
                        ),
                        (
                            "comment_from_sudocuh",
                            models.TextField(blank=True),
                        ),
                        (
                            "commentaire",
                            models.TextField(blank=True, null=True),
                        ),
                        (
                            "current_perimetre",
                            models.JSONField(null=True),
                        ),
                        (
                            "departements",
                            django.contrib.postgres.fields.ArrayField(
                                base_field=models.CharField(blank=True, max_length=3),
                                blank=True,
                                null=True,
                                verbose_name="Départements",
                            ),
                        ),
                        (
                            "doc_type_code",
                            models.TextField(blank=True, null=True),
                        ),
                        (
                            "doublon_cache_de",
                            models.OneToOneField(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.RESTRICT,
                                to="core.procedure",
                            ),
                        ),
                        (
                            "initial_perimetre",
                            models.JSONField(null=True),
                        ),
                        (
                            "is_principale",
                            models.BooleanField(blank=True, null=True),
                        ),
                        (
                            "is_sectoriel",
                            models.BooleanField(blank=True, null=True),
                        ),
                        (
                            "is_sudocuh_scot",
                            models.BooleanField(blank=True, null=True),
                        ),
                        (
                            "last_updated_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                to="users.profile",
                            ),
                        ),
                        (
                            "maitrise_d_oeuvre",
                            models.JSONField(db_column="moe", null=True),
                        ),
                        (
                            "obligation_PDU",
                            models.BooleanField(
                                blank=True, db_column="mandatory_pdu", null=True
                            ),
                        ),
                        (
                            "parente",
                            models.ForeignKey(
                                db_column="secondary_procedure_of",
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="secondaires",
                                to="core.procedure",
                            ),
                        ),
                        (
                            "previous_opposable_procedures_ids",
                            models.ForeignKey(
                                blank=True,
                                db_column="previous_opposable_procedures_ids",
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="procedures_previous_opposable_procedures_ids_set",
                                to="core.procedure",
                            ),
                        ),
                        (
                            "shareable",
                            models.BooleanField(db_default=False),
                        ),
                        (
                            "started_before_huwart_law",
                            models.BooleanField(
                                db_default=False,
                                verbose_name="lancée avant la loi Huwart",
                            ),
                        ),
                        (
                            "status",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("annule", "Annulé"),
                                    ("en cours", "En cours"),
                                    ("caduc", "Caduc"),
                                    ("abandon", "Abandon"),
                                    ("opposable", "Opposable"),
                                ],
                                null=True,
                            ),
                        ),
                        (
                            "sudocu_secondary_procedure_of",
                            models.IntegerField(blank=True, null=True),
                        ),
                        (
                            "test",
                            models.BooleanField(db_default=False),
                        ),
                        (
                            "testing",
                            models.BooleanField(blank=True, null=True),
                        ),
                        (
                            "type_code",
                            models.TextField(blank=True, null=True),
                        ),
                        (
                            "vaut_PDM",
                            models.BooleanField(
                                blank=True, db_column="is_pdu", null=True
                            ),
                        ),
                        (
                            "vaut_PLH",
                            models.BooleanField(
                                blank=True, db_column="is_pluih", null=True
                            ),
                        ),
                        (
                            "vaut_SCoT",
                            models.BooleanField(
                                blank=True, db_column="is_scot", null=True
                            ),
                        ),
                        (
                            "volet_qualitatif",
                            models.JSONField(blank=True, null=True),
                        ),
                    ],
                    options={
                        "db_table": "procedures",
                        "managed": False,
                    },
                ),
                migrations.AddIndex(
                    model_name="procedure",
                    index=models.Index(
                        models.F("created_at"), name="idx_procedures_created_at"
                    ),
                ),
                migrations.AddIndex(
                    model_name="procedure",
                    index=models.Index(
                        models.F("doc_type"), name="idx_procedures_doc_type"
                    ),
                ),
                migrations.AddIndex(
                    model_name="procedure",
                    index=models.Index(
                        fields=["id", "is_principale", "archived"],
                        name="idx_procedures_is_principale",
                    ),
                ),
                migrations.AddIndex(
                    model_name="procedure",
                    index=docurba.core.utils.OversizedIndex(
                        fields=["is_principale", "created_at"],
                        name="idx_procedures_is_principale_created_at",
                    ),
                ),
                migrations.AddIndex(
                    model_name="procedure",
                    index=docurba.core.utils.OversizedIndex(
                        fields=["is_principale", "doc_type", "created_at"],
                        name="idx_procedures_is_principale_doc_type_created_at",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="procedure",
                    constraint=models.UniqueConstraint(
                        models.F("id"),
                        condition=models.Q(("archived", False), ("parente", None)),
                        name="procedures_pkey_secondary_null_not_archived",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_insee", models.CharField(unique=True)),
                ("nom", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_insee", models.CharField(unique=True)),
                ("nom", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Collectivite",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
                (
                    "code_insee",
                    models.CharField(
                        db_comment="Peut-être vide pour une COMD ayant le même code que sa commune parente",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("COM", "Commune"),
                            ("COMD", "Commune déléguée"),
                            ("COMA", "Commune associée"),
                            ("CC", "Communauté de communes"),
                            ("SMF", "Syndicat Mixte Fermé"),
                            ("SMO", "Syndicat Mixte Ouvert"),
                            ("METRO", "Métropole"),
                            ("CU", "Communauté Urbaine"),
                            ("PETR", "Pôle d'Équilibre Territorial et Rural"),
                            ("MET69", "Métropole de Lyon"),
                            (
                                "SIVU",
                                "Syndicat Intercommunal à Vocation Unique",
                            ),
                            ("EPT", "Établissement Public Territorial"),
                            ("CA", "Communauté d'Agglomération"),
                            ("POLEM", "Pôle Métropolitain"),
                            (
                                "SIVOM",
                                "Syndicat Intercommunal à Vocation Multiple",
                            ),
                        ]
                    ),
                ),
                ("nom", models.CharField()),
                ("competence_plan", models.BooleanField(db_default=False)),
                ("competence_schema", models.BooleanField(db_default=False)),
                (
                    "adhesions",
                    models.ManyToManyField(
                        related_name="collectivites_adherentes",
                        to="core.collectivite",
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="collectivites",
                        to="core.departement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="departement",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="departements",
                to="core.region",
            ),
        ),
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "collectivite_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.collectivite",
                    ),
                ),
                (
                    "intercommunalite",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="communes",
                        to="core.collectivite",
                    ),
                ),
                (
                    "nouvelle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="deleguee",
                        to="core.commune",
                    ),
                ),
                (
                    "procedures",
                    models.ManyToManyField(
                        related_name="perimetre",
                        through="core.CommuneProcedure",
                        to="core.procedure",
                    ),
                ),
            ],
            bases=("core.collectivite",),
        ),
    ]
