# Generated by Django 5.1.5 on 2025-07-30 09:51


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_commune_collectivite_nouvelle_null_idx"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP MATERIALIZED VIEW view_core_collectivite_adhesions_deep",
            state_operations=[
                migrations.DeleteModel(
                    name="ViewCollectiviteAdhesionsDeep",
                )
            ],
        )
    ]
