# Generated by Django 5.1.5 on 2025-09-24 20:02

from typing import ClassVar

from django.db import migrations


class Migration(migrations.Migration):
    dependencies: ClassVar[list[str]] = [
        ("core", "0006_delete_viewcollectiviteadhesionsdeep"),
    ]

    operations: ClassVar[list] = [
        migrations.AlterModelOptions(
            name="event",
            options={"managed": False, "ordering": ("-date_evenement",)},
        ),
    ]
