# Generated by Django 6.0.2 on 2026-03-05 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_communeprocedure_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcedureTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="créé le",
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le", null=True
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics_through",
                        to="core.procedure",
                    ),
                ),
            ],
            options={
                "verbose_name": "objet sélectionné",
                "verbose_name_plural": "objets sélectionnés",
                "ordering": ["topic"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Nom système")),
                ("display_name", models.CharField(verbose_name="Nom d'affichage")),
                (
                    "ui_rank",
                    models.SmallIntegerField(
                        verbose_name="Position dans le menu déroulant"
                    ),
                ),
                (
                    "procedures",
                    models.ManyToManyField(
                        related_name="topics",
                        through="core.ProcedureTopic",
                        to="core.procedure",
                        verbose_name="procédures",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="proceduretopic",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="procedures_through",
                to="core.topic",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="proceduretopic",
            unique_together={("procedure", "topic")},
        ),
    ]
