# Generated by Django 6.0.2 on 2026-03-11 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_proceduretopic_topic_proceduretopic_topics_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE core_proceduretopic ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;",
            reverse_sql="ALTER TABLE core_proceduretopic ALTER COLUMN created_at DROP DEFAULT",
        )
    ]
