# Generated by Django 6.0.2 on 2026-03-03 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_proceduretopic_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["ui_rank"], "verbose_name": "objet"},
        ),
    ]
