# Generated by Django 6.0.2 on 2026-03-05 14:19

from django.db import migrations


def enable_rls(table_name: str) -> str:
    return f'alter table "{table_name}" enable row level security;'


def create_policy_auth_users_can_read_table(table_name: str) -> str:
    return f"""
        create policy "auth_users_can_read_{table_name}"
        on "public"."{table_name}"
        as PERMISSIVE
        for SELECT
        to authenticated
        using ( true );
    """


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_topic_options"),
    ]

    operations = [
        migrations.RunSQL(
            sql=enable_rls(table_name="core_topic"),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=enable_rls(table_name="core_proceduretopic"),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=create_policy_auth_users_can_read_table("core_topic"),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=create_policy_auth_users_can_read_table("core_proceduretopic"),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
