# Generated by Django 6.0.2 on 2026-03-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_topics_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="proceduretopic",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Commentaire"),
        ),
    ]
