# Generated by Django 6.0.2 on 2026-03-05 14:19

from django.db import migrations


def enable_rls(table_name: str) -> str:
    return f'alter table "{table_name}" enable row level security;'


def disable_rls(table_name: str) -> str:
    return f'alter table "{table_name}" disable row level security;'


def drop_policy(policy_name: str, table_name: str) -> str:
    return f"drop policy if exists {policy_name} on {table_name}"


def create_policy_auth_users_can_read_table(table_name: str) -> str:
    return f"""
        create policy "auth_users_can_read_{table_name}"
        on "public"."{table_name}"
        as PERMISSIVE
        for SELECT
        to authenticated
        using ( true );
    """


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_proceduretopic_comment"),
    ]

    operations = [
        migrations.RunSQL(
            sql=enable_rls(table_name="core_topic"),
            reverse_sql=disable_rls(table_name="core_topic"),
        ),
        migrations.RunSQL(
            sql=enable_rls(table_name="core_proceduretopic"),
            reverse_sql=disable_rls(table_name="core_proceduretopic"),
        ),
        migrations.RunSQL(
            sql=create_policy_auth_users_can_read_table("core_topic"),
            reverse_sql=drop_policy("auth_users_can_read_core_topic", "core_topic"),
        ),
        migrations.RunSQL(
            sql=create_policy_auth_users_can_read_table("core_proceduretopic"),
            reverse_sql=drop_policy(
                "auth_users_can_read_core_proceduretopic",
                "core_proceduretopic",
            ),
        ),
    ]
