# Generated by Django 6.0.2 on 2026-03-05 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_survey_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="proceduresurvey",
            name="departement_code",
            field=models.ForeignKey(
                db_column="departement_code",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.departement",
                to_field="code_insee",
                verbose_name="code du département",
            ),
        ),
        migrations.AddField(
            model_name="proceduresurvey",
            name="is_valid",
            field=models.BooleanField(null=True, verbose_name="est valide"),
        ),
        migrations.AddField(
            model_name="proceduresurvey",
            name="responded_at",
            field=models.DateTimeField(auto_now=True, verbose_name="répondu le le"),
        ),
    ]
