# Generated by Django 6.0.2 on 2026-03-03 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_topics_rls"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    "ALTER TABLE IF EXISTS public.procedures ADD COLUMN IF NOT EXISTS comment_from_sudocuh text NOT NULL DEFAULT ''"
                )
            ],
            reverse_sql=[
                (
                    "ALTER TABLE IF EXISTS public.procedures DROP COLUMN IF EXISTS comment_from_sudocuh"
                )
            ],
        )
    ]
