# Generated by Django 6.0.2 on 2026-03-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_proceduresurvey_departement_code_and_more"),
        ("users", "0002_add_column_departements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proceduresurvey",
            name="respondant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="surveys_answers",
                to="users.profile",
            ),
        ),
    ]
