# Generated by Django 6.0.2 on 2026-03-10 15:36

from django.db import migrations

NEW_PROCEDURES_BY_COLLECTIVITES_FUNCTION = """
DROP FUNCTION IF EXISTS procedures_by_collectivites;

CREATE FUNCTION procedures_by_collectivites(codes json)
RETURNS SETOF record
AS $$
SELECT p.*, array_agg(distinct pp.*) AS procedures_perimetres,
CASE
  WHEN count(topics) >= 1 THEN array_agg(distinct topics.display_name)
ELSE
  Null
END as topics,
CASE
  WHEN count(topics) >= 1 THEN (array_agg(topics.comment) filter(where topics.topic_id = 1))[1]
ELSE
  Null
END as topics__other__comment
    FROM procedures p
    JOIN procedures_perimetres pp ON p.id = pp.procedure_id
    left join lateral (
		select cp.procedure_id, cp.topic_id, ct.display_name, cp.comment
		from core_proceduretopic cp
		inner join core_topic ct on cp.topic_id = ct.id
    ) as topics on topics.procedure_id = p.id
    WHERE p.id IN (
        SELECT procedure_id
        FROM procedures_perimetres
        WHERE collectivite_code IN (
            SELECT json_array_elements_text(codes)
        )
    ) GROUP BY p.id;
$$ LANGUAGE sql
SECURITY INVOKER;
"""

OLD_PROCEDURES_BY_COLLECTIVITES_FUNCTION = """
DROP FUNCTION procedures_by_collectivites;
CREATE FUNCTION procedures_by_collectivites(codes json)
RETURNS SETOF record
AS $$
SELECT p.*, array_agg(pp.*) AS procedures_perimetres
    FROM procedures p
    JOIN procedures_perimetres pp ON p.id = pp.procedure_id
    WHERE p.id IN (
        SELECT procedure_id
        FROM procedures_perimetres
        WHERE collectivite_code IN (
            SELECT json_array_elements_text(codes)
        )
    ) GROUP BY p.id;
$$ LANGUAGE sql
SECURITY INVOKER;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_add_sudocuh_comment"),
    ]

    operations = [
        migrations.RunSQL(
            sql=NEW_PROCEDURES_BY_COLLECTIVITES_FUNCTION,
            reverse_sql=OLD_PROCEDURES_BY_COLLECTIVITES_FUNCTION,
        )
    ]
