# Generated by Django 6.0.2 on 2026-03-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_proceduresurvey_respondant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proceduresurvey",
            name="is_valid",
        ),
        migrations.AddField(
            model_name="proceduresurvey",
            name="is_validated",
            field=models.BooleanField(null=True, verbose_name="est validée"),
        ),
    ]
