# Generated by Django 6.0.2 on 2026-03-17 15:43

from django.db import migrations


def drop_policy(policy_name: str, table_name: str) -> str:
    return f"drop policy if exists {policy_name} on {table_name}"


def create_policy_auth_users_can_insert_core_proceduretopic() -> str:
    return """
        create policy "auth_users_can_insert_core_proceduretopic"
        on "public"."core_proceduretopic"
        as PERMISSIVE
        for INSERT
        to authenticated
        with check ( true );
    """


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_update_procedures_by_collectivites_function"),
    ]

    operations = [
        migrations.RunSQL(
            sql=create_policy_auth_users_can_insert_core_proceduretopic(),
            reverse_sql=drop_policy(
                "auth_users_can_insert_core_proceduretopic",
                "core_proceduretopic",
            ),
        ),
    ]
