# Generated by Django 6.0.2 on 2026-03-12 21:29

from django.db import migrations


def drop_policy(policy_name: str, table_name: str) -> str:
    return f"drop policy if exists {policy_name} on {table_name}"


# https://supabase.com/docs/guides/getting-started/ai-prompts/database-rls-policies
def create_policy_auth_users_can_update_table_core_proceduretopic() -> str:
    return """
        create policy "auth_users_can_update_table_core_proceduretopic"
        on "public"."core_proceduretopic"
        as PERMISSIVE
        for UPDATE
        to authenticated
        using (
            (select auth.uid() in (
                select profiles.user_id
                from profiles
                where (profiles.poste = 'ddt'))
            )
        )
        ;
    """


def create_policy_auth_users_can_delete_table_core_proceduretopic() -> str:
    return """
        create policy "auth_users_can_delete_table_core_proceduretopic"
        on "public"."core_proceduretopic"
        as PERMISSIVE
        for DELETE
        to authenticated
        using (
            (select auth.uid() in (
                select profiles.user_id
                from profiles
                where (profiles.poste = 'ddt'))
            )
        )
        ;
    """


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_topics_rls"),
    ]

    operations = [
        migrations.RunSQL(
            sql=create_policy_auth_users_can_update_table_core_proceduretopic(),
            reverse_sql=drop_policy(
                "auth_users_can_update_table_core_proceduretopic",
                "core_proceduretopic",
            ),
        ),
        migrations.RunSQL(
            sql=create_policy_auth_users_can_delete_table_core_proceduretopic(),
            reverse_sql=drop_policy(
                "auth_users_can_delete_table_core_proceduretopic",
                "core_proceduretopic",
            ),
        ),
    ]
