# Generated by Django 6.0.2 on 2026-03-12 22:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_rls_update_delete_proceduretopic"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    "ALTER TABLE public.procedures ADD COLUMN last_updated_by_id UUID REFERENCES profiles(user_id)"
                )
            ],
            reverse_sql=[
                ("ALTER TABLE public.procedures DROP COLUMN last_updated_by_id")
            ],
        )
    ]
