# Generated by Django 6.0.4 on 2026-04-10 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_add_last_updated_by_id_to_procedures"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="communeprocedure",
            options={"verbose_name": "Périmètre"},
        ),
    ]
