# Generated by Django 6.0.2 on 2026-03-05 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_add_last_updated_by_id_to_procedures"),
        ("users", "0002_add_column_departements"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcedureSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys_answers",
                        to="core.procedure",
                    ),
                ),
                (
                    "respondant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="surveys_answers",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "validation",
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True, verbose_name="nom unique")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créée le"),
                ),
                (
                    "procedures",
                    models.ManyToManyField(
                        related_name="surveys",
                        through="core.ProcedureSurvey",
                        to="core.procedure",
                        verbose_name="procédures",
                    ),
                ),
            ],
            options={
                "verbose_name": "enquête",
            },
        ),
        migrations.AddField(
            model_name="proceduresurvey",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="procedures_through",
                to="core.survey",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="proceduresurvey",
            unique_together={("procedure", "survey")},
        ),
        migrations.AddField(
            model_name="proceduresurvey",
            name="collectivite_code",
            field=models.ForeignKey(
                default=97617,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.collectivite",
                to_field="code_insee_unique",
                verbose_name="Code collectivité",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="proceduresurvey",
            name="is_validated",
            field=models.BooleanField(null=True, verbose_name="est validée"),
        ),
        migrations.AddField(
            model_name="proceduresurvey",
            name="responded_at",
            field=models.DateTimeField(auto_now=True, verbose_name="répondu le"),
        ),
    ]
