# Generated by Django 6.0.2 on 2026-03-05 14:19

from django.db import migrations


def enable_rls(table_name: str) -> str:
    return f'alter table "{table_name}" enable row level security;'


def disable_rls(table_name: str) -> str:
    return f'alter table "{table_name}" disable row level security;'


def create_policy_auth_users_can_read_table(table_name: str) -> str:
    return f"""
        create policy "auth_users_can_read_{table_name}"
        on "public"."{table_name}"
        as PERMISSIVE
        for SELECT
        to authenticated
        using ( true );
    """


def drop_policy(policy_name: str, table_name: str) -> str:
    return f"drop policy if exists {policy_name} on {table_name}"


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_proceduresurvey_survey_proceduresurvey_survey_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=enable_rls(table_name="core_survey"),
            reverse_sql=disable_rls(table_name="core_survey"),
        ),
        migrations.RunSQL(
            sql=enable_rls(table_name="core_proceduresurvey"),
            reverse_sql=disable_rls(table_name="core_proceduresurvey"),
        ),
        migrations.RunSQL(
            sql=create_policy_auth_users_can_read_table("core_survey"),
            reverse_sql=drop_policy("auth_users_can_read_core_survey", "core_survey"),
        ),
        migrations.RunSQL(
            sql=create_policy_auth_users_can_read_table("core_proceduresurvey"),
            reverse_sql=drop_policy(
                "auth_users_can_read_core_proceduresurvey", "core_proceduresurvey"
            ),
        ),
    ]
