# Generated by Django 6.0.4 on 2026-04-21 16:28

import django.contrib.postgres.functions
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models

import docurba.core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_communeprocedure_is_managed"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="communeprocedure",
                    name="added_at",
                    field=models.DateTimeField(
                        db_default=django.contrib.postgres.functions.TransactionNow(),
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="communeprocedure",
                    name="collectivite_code",
                    field=models.TextField(default=0, verbose_name="Code collectivité"),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name="communeprocedure",
                    name="collectivite_type",
                    field=models.TextField(
                        choices=[
                            ("COM", "Commune"),
                            ("COMD", "Commune déléguée"),
                            ("UNKWN", "Inconnu"),
                        ],
                        default="COM",
                        verbose_name="Type de collectivité",
                    ),
                ),
                migrations.AddField(
                    model_name="communeprocedure",
                    name="commune",
                    field=models.ForeignObject(
                        from_fields=["commune_id"],
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.commune",
                        to_fields=["collectivite_ptr_id"],
                    ),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name="communeprocedure",
                    name="procedure",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.procedure",
                    ),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name="communeprocedure",
                    name="created_at",
                    field=models.DateTimeField(
                        db_default=django.contrib.postgres.functions.TransactionNow()
                    ),
                ),
                migrations.AddField(
                    model_name="communeprocedure",
                    name="departement",
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="communeprocedure",
                    name="opposable",
                    field=models.BooleanField(
                        default=False, verbose_name="Est opposable"
                    ),
                ),
                migrations.AlterField(
                    model_name="communeprocedure",
                    name="id",
                    field=models.UUIDField(
                        db_default=django.contrib.postgres.functions.RandomUUID(),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AddIndex(
                    model_name="communeprocedure",
                    index=models.Index(fields=["departement"], name="departement_idx"),
                ),
                migrations.AddIndex(
                    model_name="communeprocedure",
                    index=docurba.core.utils.OversizedIndex(
                        fields=["procedure_id"],
                        include=("commune_id",),
                        name="procedure_including_commune_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="communeprocedure",
                    index=docurba.core.utils.OversizedIndex(
                        fields=["commune_id"],
                        name="procedures_perimetres_commune_id_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="communeprocedure",
                    index=docurba.core.utils.OversizedIndex(
                        fields=["commune_id"],
                        include=("procedure_id",),
                        name="procedures_perimetres_commune_id_including_procedure",
                    ),
                ),
                migrations.AddIndex(
                    model_name="communeprocedure",
                    index=models.Index(
                        fields=["procedure_id", "collectivite_code"], name="test_idx"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="communeprocedure",
                    constraint=models.UniqueConstraint(
                        fields=("collectivite_code", "procedure", "collectivite_type"),
                        name="uniq_perimeters_collectivite_procedure_type_couple_ids",
                    ),
                ),
                migrations.AddField(
                    model_name="communeprocedure",
                    name="commune_id",
                    field=models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            "collectivite_code", models.Value("_"), "collectivite_type"
                        ),
                        output_field=models.TextField(),
                    ),
                ),
            ],
        )
    ]
