# Generated by Django 6.0.4 on 2026-05-01 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_communeprocedure_state"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    "ALTER TABLE IF EXISTS public.procedures ADD COLUMN IF NOT EXISTS started_before_huwart_law bool NOT NULL DEFAULT False"
                )
            ],
            reverse_sql=[
                (
                    "ALTER TABLE IF EXISTS public.procedures DROP COLUMN IF EXISTS started_before_huwart_law"
                )
            ],
        )
    ]
