# Generated by Django 6.0.4 on 2026-05-12 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_add_started_before_huwart_law"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communeprocedure",
            name="procedure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perimetre_through",
                to="core.procedure",
            ),
        ),
    ]
