# ruff: noqa: ERA001
# Generated by Django 6.0.4 on 2026-05-07 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_alter_communeprocedure_procedure"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # The following SQL was run manually on commit 57bcbdc01d3a7f69bf75343163c66ab79684bfde
            # and on PR https://github.com/MTES-MCT/Docurba/pull/1429
            # but was not reflected on a migration.
            # migrations.RunSQL(
            #     sql="ALTER TABLE doc_frise_events ALTER COLUMN date_iso TYPE date USING date_iso::date",
            #     reverse_sql="ALTER TABLE doc_frise_events ALTER COLUMN date_iso TYPE varchar USING date_iso::varchar",
            # )
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name="event",
                    old_name="date_evenement_string",
                    new_name="date_evenement",
                )
            ],
        ),
    ]
