# Generated by Django 6.0.4 on 2026-05-07 13:09

from datetime import date

from django.db import migrations


def delete_fin_echeance(apps, schema_editor) -> None:  # noqa: ANN001, ARG001
    Event = apps.get_model("core", "Event")
    Event.objects.filter(
        date_evenement__gt=date(2025, 11, 28), type="Fin d'échéance"
    ).delete()  # 406


DISABLE_TRIGGERS = """
    ALTER TABLE doc_frise_events
        DISABLE TRIGGER handle_updated_at,
        DISABLE TRIGGER trigger_event_procedure_status_handler;
"""

ENABLE_TRIGGERS = """
    ALTER TABLE doc_frise_events
        ENABLE TRIGGER handle_updated_at,
        ENABLE TRIGGER trigger_event_procedure_status_handler;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_alter_date_evenement_string"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DISABLE_TRIGGERS, reverse_sql=ENABLE_TRIGGERS, elidable=True
        ),
        migrations.RunPython(
            delete_fin_echeance,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.RunSQL(
            sql=ENABLE_TRIGGERS, reverse_sql=DISABLE_TRIGGERS, elidable=True
        ),
    ]
