# Generated by Django 6.0.5 on 2026-05-21 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_delete_fin_echeance_events"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP FUNCTION IF EXISTS public.events_duplicate_by_procedures_ids;
                DROP TABLE IF EXISTS doc_frise_events_duplicate;
                """,
            reverse_sql="""
                CREATE TABLE doc_frise_events_duplicate (procedure_id uuid);

                CREATE FUNCTION public.events_duplicate_by_procedures_ids(procedures_ids json) RETURNS SETOF record
                    LANGUAGE sql
                    AS $$
                SELECT *
                FROM doc_frise_events_duplicate
                WHERE procedure_id::text IN (SELECT value FROM jsonb_array_elements_text(procedures_ids::jsonb));
                $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DROP INDEX test_index;
            """,
            reverse_sql="""
                CREATE INDEX test_index ON public.doc_frise_events USING btree (procedure_id, date_iso);
            """,
        ),
    ]
