# Generated by Django 6.0.5 on 2026-05-22 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_remove_unused_index_and_functions_doc_frise_events"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "managed": False,
                "ordering": ("-date_evenement",),
                "verbose_name": "évènement",
            },
        ),
    ]
