# Generated by Django 6.0.5 on 2026-05-22 12:51

from django.conf import settings
from django.db import migrations

DISABLE_TRIGGER = """
    ALTER TABLE doc_frise_events
        DISABLE TRIGGER trigger_event_procedure_status_handler;
"""

ENABLE_TRIGGER = """
    ALTER TABLE doc_frise_events
        ENABLE TRIGGER trigger_event_procedure_status_handler;
"""


def event_procedure_status_handler_sql(nuxt_url: str) -> str:
    return f"""
        CREATE OR REPLACE FUNCTION public.event_procedure_status_handler() RETURNS trigger
            LANGUAGE plpgsql
            AS $$ declare procedure procedures; event_processed doc_frise_events;
            BEGIN
                IF TG_OP = 'UPDATE' OR TG_OP = 'INSERT' then event_processed := new;
                else event_processed := old;
                END IF;
                SELECT * into procedure FROM procedures WHERE id = event_processed.procedure_id;
                PERFORM set_procedure_status(procedure);
                /* NUXT3_API_URL is hardcoded here because this dump will disappear soon and I don't know how to change it quickly in SQL. */
                PERFORM net.http_get('{nuxt_url}/api/urba/procedures/' || event_processed.procedure_id || '/update');
            return event_processed; END; $$;
        """  # noqa: S608


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_alter_event_options"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DISABLE_TRIGGER,
            reverse_sql=ENABLE_TRIGGER,
        ),
        migrations.RunSQL(
            sql=event_procedure_status_handler_sql(nuxt_url=settings.NUXT3_API_URL),
            reverse_sql=event_procedure_status_handler_sql(nuxt_url=""),
        ),
        migrations.RunSQL(
            sql=ENABLE_TRIGGER,
            reverse_sql=DISABLE_TRIGGER,
        ),
    ]
