# Generated by Django 6.0.5 on 2026-06-02 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_update_nuxt3_trigger"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""ALTER TABLE "doc_frise_events"
            ALTER COLUMN "actors" SET DATA TYPE jsonb,
            ALTER COLUMN "attachements" SET DATA TYPE jsonb
            """,
            reverse_sql="""ALTER TABLE "doc_frise_events"
            ALTER COLUMN "actors" SET DATA TYPE json,
            ALTER COLUMN "attachements" SET DATA TYPE json
            """,
        )
    ]
