# Generated by Django 6.0.5 on 2026-06-02 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_event_alter_json_types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "base_manager_name": "objects",
                "managed": False,
                "ordering": ("-date_evenement",),
                "verbose_name": "évènement",
            },
        ),
    ]
