# Generated by Django 6.0.5 on 2026-06-02 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_alter_event_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "base_manager_name": "objects",
                "ordering": ("-date_evenement",),
                "verbose_name": "évènement",
            },
        ),
    ]
