# Generated by Django 6.0.5 on 2026-06-02 14:55

from django.db import migrations, models

import docurba.core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_make_events_managed"),
        ("users", "0002_add_column_departements"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name="event",
                    index=models.Index(
                        models.F("procedure"),
                        models.OrderBy(models.F("date_evenement"), descending=True),
                        models.F("type"),
                        models.F("is_valid"),
                        name="aaaaa",
                    ),
                ),
                migrations.AddIndex(
                    model_name="event",
                    index=docurba.core.utils.OversizedIndex(
                        models.F("procedure"),
                        models.OrderBy(models.F("date_evenement"), descending=True),
                        name="idx_doc_frise_events_procedure_id_date_iso",
                    ),
                ),
                migrations.AlterField(
                    model_name="event",
                    name="date_evenement",
                    field=models.DateField(
                        db_column="date_iso", null=True, verbose_name="date"
                    ),
                ),
            ],
        )
    ]
