# Generated by Django 6.0.5 on 2026-06-03 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_reference_indexes_and_col_update"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="procedure",
            options={"base_manager_name": "objects"},
        ),
    ]
