# Generated by Django 6.0.5 on 2026-06-04 14:47

import django.contrib.postgres.functions
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_make_procedures_managed"),
        ("pghistory", "0007_auto_20250421_0444"),
        ("users", "0003_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventsSnapshot",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.contrib.postgres.functions.RandomUUID(),
                        editable=False,
                        serialize=False,
                    ),
                ),
                ("type", models.TextField(blank=True, null=True)),
                (
                    "date_evenement",
                    models.DateField(
                        db_column="date_iso", null=True, verbose_name="date"
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(db_default=True, verbose_name="est valide"),
                ),
                (
                    "visibility",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("public", "Publique - Visible par le grand public"),
                            (
                                "private",
                                "Privé - Visible uniquement par les collaborateur·ices de la procédure",
                            ),
                        ],
                        db_default="public",
                        null=True,
                        verbose_name="visibilité",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        db_default=django.contrib.postgres.functions.TransactionNow(),
                        null=True,
                        verbose_name="créé le",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        db_default=django.contrib.postgres.functions.TransactionNow(),
                        null=True,
                        verbose_name="modifié le",
                    ),
                ),
                (
                    "attachements",
                    models.JSONField(
                        blank=True, null=True, verbose_name="pièces-jointes"
                    ),
                ),
                (
                    "from_sudocuh",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="from_sudocuh"
                    ),
                ),
                (
                    "actors",
                    models.JSONField(blank=True, null=True, verbose_name="acteurs"),
                ),
                (
                    "is_sudocuh_scot",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="is_sudocuh_scot"
                    ),
                ),
                ("test", models.BooleanField(blank=True, null=True)),
                ("code", models.TextField(blank=True, null=True)),
                (
                    "from_sudocuh_procedure_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="from_sudocuh_procedure_id"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="event",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_eventssnapshot" ("actors", "attachements", "code", "created_at", "date_iso", "description", "from_sudocuh", "from_sudocuh_procedure_id", "id", "is_sudocuh_scot", "is_valid", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "procedure_id", "profile_id", "project_id", "test", "type", "updated_at", "visibility") VALUES (NEW."actors", NEW."attachements", NEW."code", NEW."created_at", NEW."date_iso", NEW."description", NEW."from_sudocuh", NEW."from_sudocuh_procedure_id", NEW."id", NEW."is_sudocuh_scot", NEW."is_valid", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."procedure_id", NEW."profile_id", NEW."project_id", NEW."test", NEW."type", NEW."updated_at", NEW."visibility"); RETURN NULL;',
                    hash="838d97f1b64e29e324ecf1804c37a0560e54ddb0",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_137f2",
                    table="doc_frise_events",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="event",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_eventssnapshot" ("actors", "attachements", "code", "created_at", "date_iso", "description", "from_sudocuh", "from_sudocuh_procedure_id", "id", "is_sudocuh_scot", "is_valid", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "procedure_id", "profile_id", "project_id", "test", "type", "updated_at", "visibility") VALUES (NEW."actors", NEW."attachements", NEW."code", NEW."created_at", NEW."date_iso", NEW."description", NEW."from_sudocuh", NEW."from_sudocuh_procedure_id", NEW."id", NEW."is_sudocuh_scot", NEW."is_valid", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."procedure_id", NEW."profile_id", NEW."project_id", NEW."test", NEW."type", NEW."updated_at", NEW."visibility"); RETURN NULL;',
                    hash="cad88e54c4f47e16abc36a0c0bddeb5ea100e9c9",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_d4328",
                    table="doc_frise_events",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="eventssnapshot",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="eventssnapshot",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="core.event",
            ),
        ),
        migrations.AddField(
            model_name="eventssnapshot",
            name="procedure",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="core.procedure",
                verbose_name="procédure",
            ),
        ),
        migrations.AddField(
            model_name="eventssnapshot",
            name="profile",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="users.profile",
                verbose_name="profil",
            ),
        ),
        migrations.AddField(
            model_name="eventssnapshot",
            name="project",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="core.project",
            ),
        ),
    ]
