# Generated by Django 6.0.5 on 2026-06-09 12:21

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_make_procedures_managed"),
        ("history", "0002_events_initial_snapshots"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="event",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "history_eventsnapshot" ("code", "date_iso", "description", "from_sudocuh", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "procedure_id", "profile_id", "type") VALUES (NEW."code", NEW."date_iso", NEW."description", NEW."from_sudocuh", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."procedure_id", NEW."profile_id", NEW."type"); RETURN NULL;',
                    hash="9ca1c8fa293981158c058a17c7882481294b947b",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_137f2",
                    table="doc_frise_events",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="event",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."code" IS DISTINCT FROM (NEW."code") OR OLD."date_iso" IS DISTINCT FROM (NEW."date_iso") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."from_sudocuh" IS DISTINCT FROM (NEW."from_sudocuh") OR OLD."procedure_id" IS DISTINCT FROM (NEW."procedure_id") OR OLD."profile_id" IS DISTINCT FROM (NEW."profile_id") OR OLD."type" IS DISTINCT FROM (NEW."type"))',
                    func='INSERT INTO "history_eventsnapshot" ("code", "date_iso", "description", "from_sudocuh", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "procedure_id", "profile_id", "type") VALUES (NEW."code", NEW."date_iso", NEW."description", NEW."from_sudocuh", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."procedure_id", NEW."profile_id", NEW."type"); RETURN NULL;',
                    hash="c6e6492513b8ab6a100b7930406a3a598c197202",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_d4328",
                    table="doc_frise_events",
                    when="AFTER",
                ),
            ),
        ),
    ]
