# Generated by Django 6.0.6 on 2026-06-16 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_events_history_kickoff"),
        ("users", "0003_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date_evenement",
            field=models.DateField(
                blank=True, db_column="date_iso", null=True, verbose_name="date"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.profile",
                verbose_name="profil",
            ),
        ),
    ]
