# Generated by Django 6.0.6 on 2026-06-16 09:18

from django.db import migrations

NEW_PROCEDURES_BY_COLLECTIVITES_FUNCTION = """
DROP FUNCTION IF EXISTS procedures_by_collectivites;

CREATE FUNCTION procedures_by_collectivites(codes json)
RETURNS SETOF record
AS $$
SELECT p.*, array_agg(distinct pp.*) AS procedures_perimetres,
CASE
    WHEN count(topics) >= 1 THEN array_agg(distinct topics.display_name)
ELSE
    Null
END as topics,
CASE
    WHEN count(topics) >= 1 THEN (array_agg(topics.comment) filter(where topics.topic_id = 1))[1]
ELSE
    Null
END as topics__other__comment,
(
    SELECT array_agg(dfe)
    FROM doc_frise_events dfe
    WHERE dfe.procedure_id = p.id
) AS doc_frise_events
FROM procedures p
LEFT JOIN doc_frise_events dfe ON p.id = dfe.procedure_id
JOIN procedures_perimetres pp ON p.id = pp.procedure_id
LEFT JOIN LATERAL (
    SELECT cp.procedure_id, cp.topic_id, ct.display_name, cp.comment
    FROM core_proceduretopic cp
    INNER JOIN core_topic ct ON cp.topic_id = ct.id
) AS topics ON topics.procedure_id = p.id
WHERE p.id IN (
    SELECT procedure_id
    FROM procedures_perimetres
    WHERE collectivite_code IN (
        SELECT json_array_elements_text(codes)
    )
) GROUP BY p.id;
$$ LANGUAGE sql
SECURITY INVOKER;
"""

OLD_PROCEDURES_BY_COLLECTIVITES_FUNCTION = """
DROP FUNCTION IF EXISTS procedures_by_collectivites;

CREATE FUNCTION procedures_by_collectivites(codes json)
RETURNS SETOF record
AS $$
SELECT p.*, array_agg(distinct pp.*) AS procedures_perimetres,
CASE
  WHEN count(topics) >= 1 THEN array_agg(distinct topics.display_name)
ELSE
  Null
END as topics,
CASE
  WHEN count(topics) >= 1 THEN (array_agg(topics.comment) filter(where topics.topic_id = 1))[1]
ELSE
  Null
END as topics__other__comment
    FROM procedures p
    JOIN procedures_perimetres pp ON p.id = pp.procedure_id
    left join lateral (
		select cp.procedure_id, cp.topic_id, ct.display_name, cp.comment
		from core_proceduretopic cp
		inner join core_topic ct on cp.topic_id = ct.id
    ) as topics on topics.procedure_id = p.id
    WHERE p.id IN (
        SELECT procedure_id
        FROM procedures_perimetres
        WHERE collectivite_code IN (
            SELECT json_array_elements_text(codes)
        )
    ) GROUP BY p.id;
$$ LANGUAGE sql
SECURITY INVOKER;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_alter_event_date_evenement_alter_event_profile"),
    ]

    operations = [
        migrations.RunSQL(
            sql=NEW_PROCEDURES_BY_COLLECTIVITES_FUNCTION,
            reverse_sql=OLD_PROCEDURES_BY_COLLECTIVITES_FUNCTION,
        )
    ]
