# Generated by Django 6.0.6 on 2026-06-18 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_alter_event_date_evenement_alter_event_profile"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP FUNCTION IF EXISTS public.get_event_status;
                """,
            reverse_sql="""
                CREATE FUNCTION public.get_event_status(p_id uuid, doc_type text) RETURNS text
                    LANGUAGE plpgsql
                    AS $$
                DECLARE
                    event_record doc_frise_events%ROWTYPE;
                    new_status TEXT;
                    current_date_opposable DATE;
                BEGIN
                    FOR event_record IN
                        SELECT *
                        FROM doc_frise_events
                        WHERE procedure_id = p_id
                        AND (is_valid = true OR type = 'Abandon')
                        ORDER BY date_iso DESC, type
                    LOOP
                        new_status := get_event_impact(event_record, doc_type);

                        IF new_status = 'opposable' THEN
                            current_date_opposable := event_record.date_iso;
                        END IF;

                        IF new_status IS NOT NULL THEN
                            EXIT;
                        END IF;
                    END LOOP;

                    IF new_status IS NULL THEN
                        new_status := 'en cours';
                    END IF;

                    RETURN new_status;
                END $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DROP FUNCTION IF EXISTS public.one_shot_events;
            """,
            reverse_sql="""
                CREATE FUNCTION public.one_shot_events() RETURNS void
                    LANGUAGE plpgsql
                    AS $$
                DECLARE
                    procedure procedures;
                    start_time timestamp := clock_timestamp();
                    end_time timestamp;
                    execution_time interval;
                    i INT := 0;
                BEGIN
                    RAISE LOG 'Processing One shot events';
                    UPDATE procedures SET status = null;
                    FOR procedure IN SELECT * FROM procedures WHERE is_principale IS TRUE LOOP i := i + 1;
                        RAISE LOG 'Processing procedure events N: %', i;
                        PERFORM set_procedure_status(procedure);
                    END LOOP;
                    end_time := clock_timestamp();
                    execution_time := end_time - start_time;
                    RAISE LOG 'FUNCTION ONE SHOT execution time: %', execution_time;
                END; $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DROP FUNCTION IF EXISTS public.procedure_status_handler;
            """,
            reverse_sql="""
                CREATE FUNCTION public.procedure_status_handler() RETURNS trigger
                    LANGUAGE plpgsql
                    AS $$
                DECLARE
                    procedure procedures;
                BEGIN
                    IF TG_OP = 'UPDATE' OR TG_OP = 'INSERT' then
                        procedure := new;
                    else
                        procedure := old;
                    END IF;

                    PERFORM set_procedure_status(procedure);

                    -- Perform the HTTP GET request
                    -- TODO(cms): API call is disabled here because Nuxt3 does not listen on test mode.
                    -- PERFORM http_get('localhost:4000/api/urba/procedures/' || procedure.id || '/update');
                    return procedure;
                END;
                $$;
            """,
        ),
    ]
