# Generated by Django 6.0.6 on 2026-06-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_add_communes_procedures_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedure",
            name="doc_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CC", "Cc"),
                    ("SCOT", "Scot"),
                    ("SD", "Sd"),
                    ("PLU", "Plu"),
                    ("POS", "Pos"),
                    ("PLUi", "Plui"),
                    ("PLUiH", "Pluih"),
                    ("PLUiHM", "Pluihm"),
                    ("PLUiM", "Pluim"),
                    ("PLUiS", "Pluis"),
                    ("PLUiSH", "Pluish"),
                    ("PLUiSHM", "Pluishm"),
                    ("PLUiSM", "Pluism"),
                ],
                null=True,
            ),
        ),
    ]
