# Generated by Django 6.0.6 on 2026-06-25 14:24

from django.db import migrations


def drop_policy(policy_name: str, table_name: str) -> str:
    return f"drop policy if exists {policy_name} on {table_name}"


def create_policy_users_can_read_doc_frise_events() -> str:
    return """
        CREATE POLICY "Users Can Read" ON public.doc_frise_events FOR SELECT USING (true);
    """


def users_can_read_public_events_on_doc_frise_events() -> str:
    return """
        create policy "users_can_read_public_events_on_doc_frise_events"
        on "public"."doc_frise_events"
        for SELECT
        using (
            visibility = 'public'
        )
    """


def verified_users_can_read_private_events_on_doc_frise_events() -> str:
    return """
        create policy "verified_users_can_read_private_events_on_doc_frise_events"
        on "public"."doc_frise_events"
        as RESTRICTIVE
        for SELECT
        to authenticated
        using (
            (select auth.uid() in (
                select profiles.user_id
                from profiles
                where (profiles.verified = True))
            )
            and visibility = 'private'
        )
        ;
    """


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_add_communes_procedures_events"),
    ]

    operations = [
        migrations.RunSQL(
            sql=drop_policy('"Users Can Read"', "doc_frise_events"),
            reverse_sql=create_policy_users_can_read_doc_frise_events(),
        ),
        migrations.RunSQL(
            sql=users_can_read_public_events_on_doc_frise_events(),
            reverse_sql=drop_policy(
                "users_can_read_public_events_on_doc_frise_events",
                "doc_frise_events",
            ),
        ),
        migrations.RunSQL(
            sql=verified_users_can_read_private_events_on_doc_frise_events(),
            reverse_sql=drop_policy(
                "verified_users_can_read_private_events_on_doc_frise_events",
                "doc_frise_events",
            ),
        ),
    ]
