# Generated by Django 6.0.6 on 2026-06-26 06:49

import django.contrib.postgres.fields
import django.contrib.postgres.functions
import django.core.validators
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_add_communes_procedures_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.contrib.postgres.functions.RandomUUID(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(unique=True, verbose_name="nom")),
                (
                    "type_document",
                    models.CharField(
                        choices=[("PLU", "PLU"), ("CC", "CC"), ("SCOT", "SCOT")],
                        verbose_name="catégorie",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="priorité",
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EN_COURS", "En cours"),
                            ("ABANDON", "Abandon"),
                            ("OPPOSABLE", "Opposable"),
                            ("ANNULE", "Annulé"),
                        ],
                    ),
                ),
                ("structurant", models.BooleanField(default=False)),
                (
                    "scope_liste",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("pp", "Procédure principale"),
                                ("ppi", "Procédure principale intercommunale"),
                                ("rms", "Révision allégée ou à modalité simplifiée"),
                                ("m", "Modification (antérieur loi Huwart)"),
                                ("ms", "Modification simplifiée"),
                                ("mc", "Mise en compatibilité"),
                                ("mj", "Mise à jour"),
                                ("mlh", "Modification (postérieur loi Huwart)"),
                            ]
                        ),
                        default=list,
                        verbose_name="liste des scopes",
                    ),
                ),
                (
                    "scope_sugg",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("pp", "Procédure principale"),
                                ("ppi", "Procédure principale intercommunale"),
                                ("rms", "Révision allégée ou à modalité simplifiée"),
                                ("m", "Modification (antérieur loi Huwart)"),
                                ("ms", "Modification simplifiée"),
                                ("mc", "Mise en compatibilité"),
                                ("mj", "Mise à jour"),
                                ("mlh", "Modification (postérieur loi Huwart)"),
                            ]
                        ),
                        default=list,
                        verbose_name="Scopes suggérés",
                    ),
                ),
                (
                    "sudocuh_name",
                    models.CharField(blank=True, verbose_name="nom sudocuh"),
                ),
                (
                    "sudocuh_code",
                    models.CharField(blank=True, verbose_name="code sudocuh"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="créé le",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="mis à jour le"
                    ),
                ),
            ],
            options={
                "verbose_name": "Type d'évènement",
            },
        ),
    ]
