# Generated by Django 6.0.6 on 2026-06-25 14:24

from django.db import migrations


def drop_policy(policy_name: str, table_name: str) -> str:
    return f"drop policy if exists {policy_name} on {table_name}"


def users_can_access_etapes_versement() -> str:
    return """
        CREATE POLICY "Policy with security definer functions" ON public.etapes_versement USING (true);
    """


def authenticated_users_can_access_versements() -> str:
    return """
        CREATE POLICY "Policy with security definer functions" ON public.versements TO authenticated USING (true);
    """


def verified_users_can_access_versements() -> str:
    return """
        CREATE POLICY "verified_users_can_access_versements" ON public.versements USING ((
        SELECT profiles.verified
            FROM public.profiles
            WHERE (auth.uid() = profiles.user_id)
        ));
    """


def verified_users_can_access_etapes_versement() -> str:
    return """
        CREATE POLICY "verified_users_can_access_etapes_versement" ON public.etapes_versement USING ((
        SELECT profiles.verified
            FROM public.profiles
            WHERE (auth.uid() = profiles.user_id)
        ));
    """


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_alter_procedure_doc_type"),
    ]

    operations = [
        migrations.RunSQL(
            sql=drop_policy(
                '"Policy with security definer functions"', "etapes_versement"
            ),
            reverse_sql=users_can_access_etapes_versement(),
        ),
        migrations.RunSQL(
            sql=drop_policy('"Policy with security definer functions"', "versements"),
            reverse_sql=authenticated_users_can_access_versements(),
        ),
        migrations.RunSQL(
            sql=verified_users_can_access_etapes_versement(),
            reverse_sql=drop_policy(
                "verified_users_can_access_etapes_versement",
                "etapes_versement",
            ),
        ),
        migrations.RunSQL(
            sql=verified_users_can_access_versements(),
            reverse_sql=drop_policy(
                "verified_users_can_access_versements",
                "versements",
            ),
        ),
    ]
