# Generated by Django 6.0.6 on 2026-06-30 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_update_rls_on_versements"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.CreateModel(
                    name="Adhesion",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "from_collectivite",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="to_collectivite_through",
                                to="core.collectivite",
                                verbose_name="groupement",
                            ),
                        ),
                        (
                            "to_collectivite",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.RESTRICT,
                                related_name="from_collectivite_through",
                                to="core.collectivite",
                                verbose_name="membre",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "adhésion",
                        "verbose_name_plural": "adhésions",
                        "db_table": "core_collectivite_adhesions",
                        "unique_together": {("from_collectivite", "to_collectivite")},
                    },
                ),
                migrations.AlterField(
                    model_name="collectivite",
                    name="adhesions",
                    field=models.ManyToManyField(
                        related_name="collectivites_adherentes",
                        through="core.Adhesion",
                        to="core.collectivite",
                    ),
                ),
            ],
        )
    ]
