# Generated by Django 6.0.6 on 2026-06-26 12:00
from django.contrib.postgres import functions
from django.db import migrations, models


def create_view() -> str:
    return """
        CREATE MATERIALIZED VIEW IF NOT EXISTS materialized_view_flat_memberships AS
            WITH RECURSIVE
                adhesion_paths AS (
                    SELECT
                        from_collectivite_id,
                        to_collectivite_id,
                        from_collectivite.type as from_collectivite_type,
                        to_collectivite.type as to_collectivite_type
                    FROM
                        core_collectivite_adhesions
                        inner join core_collectivite as from_collectivite on from_collectivite.id = core_collectivite_adhesions.from_collectivite_id
                        inner join core_collectivite as to_collectivite on to_collectivite.id = core_collectivite_adhesions.to_collectivite_id
                    UNION
                    SELECT
                        adhesion_paths.from_collectivite_id,
                        core_collectivite_adhesions.to_collectivite_id,
                        from_collectivite_inner.type as from_collectivite_type,
                        to_collectivite_inner.type as to_collectivite_type
                    FROM
                        adhesion_paths
                        JOIN core_collectivite_adhesions ON core_collectivite_adhesions.from_collectivite_id = adhesion_paths.to_collectivite_id
                        INNER JOIN core_collectivite as from_collectivite_inner on from_collectivite_inner.id = adhesion_paths.from_collectivite_id
                        inner join core_collectivite as to_collectivite_inner on to_collectivite_inner.id = core_collectivite_adhesions.to_collectivite_id
                )
        SELECT
            gen_random_uuid() as id,
            from_collectivite_id as member_id,
            to_collectivite_id as group_id,
            from_collectivite_type as member_type,
            to_collectivite_type as group_type
        FROM
            adhesion_paths
        group by
            member_id, group_id, member_type, group_type
        ;
    """


def create_indexes() -> str:
    return """
        CREATE INDEX member_id_idx ON materialized_view_flat_memberships (member_id varchar_pattern_ops) include (group_id);
        CREATE INDEX group_id_idx ON materialized_view_flat_memberships (group_id varchar_pattern_ops) include (member_id);
        CREATE INDEX group_id_member_type_idx ON materialized_view_flat_memberships (group_id, member_type) include (member_id);
        CREATE INDEX member_id_group_type_idx ON materialized_view_flat_memberships (member_id, group_type) include (group_id);
        CREATE INDEX member_type_idx ON materialized_view_flat_memberships (member_type);
    """


def drop_indexes() -> str:
    return """
        DROP INDEX member_id_idx;
        DROP INDEX group_id_idx;
        DROP INDEX group_id_member_type_idx;
        DROP INDEX member_id_group_type_idx;
        DROP INDEX member_type_idx;
    """


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_adhesion_alter_collectivite_adhesions"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=create_view(),
                    reverse_sql="DROP MATERIALIZED VIEW IF EXISTS materialized_view_flat_memberships",
                ),
                migrations.RunSQL(
                    sql=create_indexes(),
                    reverse_sql=drop_indexes(),
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="MaterializedViewFlatMembership",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                db_default=functions.RandomUUID(),
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "member",
                            models.ForeignKey(
                                on_delete=models.DO_NOTHING,
                                related_name="flat_groups_through",
                                to="core.Collectivite",
                                verbose_name="Membre",
                            ),
                        ),
                        (
                            "group",
                            models.ForeignKey(
                                on_delete=models.DO_NOTHING,
                                related_name="flat_members_through",
                                to="core.Collectivite",
                                verbose_name="Groupement",
                            ),
                        ),
                        ("member_type", models.CharField(blank=True, null=True)),
                        ("group_type", models.CharField(blank=True, null=True)),
                    ],
                    options={
                        "db_table": "materialized_view_flat_memberships",
                        "managed": False,
                    },
                ),
                migrations.AddField(
                    model_name="collectivite",
                    name="flat_groups",
                    field=models.ManyToManyField(
                        related_name="flat_members",
                        through="core.MaterializedViewFlatMembership",
                        to="core.collectivite",
                    ),
                ),
            ],
        )
    ]
