# Generated by Django 6.0.6 on 2026-06-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_create_flat_memberships"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectivite",
            name="siren",
            field=models.CharField(blank=True, max_length=9, verbose_name="SIREN"),
        ),
    ]
