# Generated by Django 6.0.6 on 2026-06-30 15:22

from django.db import migrations, models
from django.db.models.functions import Length


def fill_siren(apps, schema_editor) -> None:  # noqa: ANN001, ARG001
    Collectivite = apps.get_model("core", "Collectivite")
    Collectivite.objects.annotate(
        code_insee_unique_length=Length("code_insee_unique")
    ).filter(code_insee_unique_length__gte=9).update(
        siren=models.F("code_insee_unique")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_collectivite_siren"),
    ]

    operations = [
        migrations.RunPython(
            fill_siren, reverse_code=migrations.RunPython.noop, elidable=True
        )
    ]
