# Generated by Django 6.0.6 on 2026-07-01 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_fill_siren_from_code_insee_unique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commune",
            name="adhesions_deep",
        ),
        migrations.DeleteModel(
            name="ViewCommuneAdhesionsDeep",
        ),
    ]
