# Generated by Django 6.0.6 on 2026-07-06 07:07

import json
import pathlib

import django.contrib.postgres.fields
import django.contrib.postgres.functions
import django.core.validators
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models, transaction

from docurba.utils.enums import DocurbaEnvironment


def create_event_types(apps, schema_editor) -> None:  # noqa: ANN001, ARG001

    if settings.DOCURBA_ENVIRONMENT == DocurbaEnvironment.TEST:
        return

    EventType = apps.get_model("core", "EventType")
    json_path = pathlib.Path(settings.APPS_DIR) / "core/data/event_types.json"
    with json_path.open("rb") as fp:
        event_types = json.load(fp)
    with transaction.atomic():
        for event_type in event_types:
            EventType.objects.update_or_create(
                pk=event_type["pk"],
                defaults=event_type["fields"],
            )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_remove_commune_adhesions_deep_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.contrib.postgres.functions.RandomUUID(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[("PLU", "Plu"), ("CC", "Cc"), ("SCOT", "Scot")],
                        verbose_name="type de document",
                    ),
                ),
                ("name", models.CharField(verbose_name="nom")),
                (
                    "order",
                    models.PositiveIntegerField(
                        blank=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="ordre",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_default=True, default=True, verbose_name="actif"
                    ),
                ),
                (
                    "is_structuring",
                    models.BooleanField(
                        db_default=False, default=False, verbose_name="structurant"
                    ),
                ),
                (
                    "scope_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("pp", "Procédure principale"),
                                ("ppi", "Procédure principale intercommunale"),
                                ("rms", "Révision allégée ou à modalité simplifiée"),
                                ("m", "Modification (antérieur loi Huwart)"),
                                ("ms", "Modification simplifiée"),
                                ("mc", "Mise en compatibilité"),
                                ("mj", "Mise à jour"),
                                ("mlh", "Modification (postérieur loi Huwart)"),
                            ]
                        ),
                        blank=True,
                        db_default="{}",
                        default=list,
                        verbose_name="liste des scopes",
                    ),
                ),
                (
                    "scope_sugg",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("pp", "Procédure principale"),
                                ("ppi", "Procédure principale intercommunale"),
                                ("rms", "Révision allégée ou à modalité simplifiée"),
                                ("m", "Modification (antérieur loi Huwart)"),
                                ("ms", "Modification simplifiée"),
                                ("mc", "Mise en compatibilité"),
                                ("mj", "Mise à jour"),
                                ("mlh", "Modification (postérieur loi Huwart)"),
                            ]
                        ),
                        blank=True,
                        db_default="{}",
                        default=list,
                        verbose_name="Scopes suggérés",
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("annule", "Annulé"),
                            ("en cours", "En cours"),
                            ("caduc", "Caduc"),
                            ("abandon", "Abandon"),
                            ("opposable", "Opposable"),
                        ],
                        db_default="",
                        default="",
                    ),
                ),
                (
                    "sudocuh_name",
                    models.CharField(
                        blank=True,
                        db_default="",
                        default="",
                        verbose_name="nom sudocuh",
                    ),
                ),
                (
                    "sudocuh_code",
                    models.CharField(
                        blank=True,
                        db_default="",
                        default="",
                        verbose_name="code sudocuh",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="créé le",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="mis à jour le"
                    ),
                ),
            ],
            options={
                "verbose_name": "type d'évènement",
                "verbose_name_plural": "types d'évènement",
                "ordering": ("order",),
                "unique_together": {("document_type", "name")},
            },
        ),
        migrations.RunPython(
            create_event_types,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
