# Generated by Django 6.0.6 on 2026-07-07 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_add_event_types"),
        ("users", "0004_add_encrypted_password_to_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="archivé le"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="users.profile",
                verbose_name="archivé par",
            ),
        ),
    ]
