# Generated by Django 6.0.2 on 2026-03-05 14:19

from django.db import migrations


def enable_rls(table_name: str) -> str:
    return f'alter table "{table_name}" enable row level security;'


def disable_rls(table_name: str) -> str:
    return f'alter table "{table_name}" disable row level security;'


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_add_event_archived"),
    ]

    operations = [
        migrations.RunSQL(
            sql=enable_rls(table_name="core_eventtype"),
            reverse_sql=disable_rls(table_name="core_eventtype"),
        ),
    ]
