# Generated by Django 6.0.6 on 2026-07-08 09:21

from django.db import migrations, models


def fill_code_insee(apps, schema_editor) -> None:  # noqa: ANN001, ARG001
    Commune = apps.get_model("core", "Commune")
    Commune.objects.exclude(code_insee_unique__isnull=True).update(
        code_insee=models.F("code_insee_unique")
    )
    communes_qs = Commune.objects.filter(code_insee_unique__isnull=True).annotate(
        nouvelle_code_insee=models.F("nouvelle__code_insee")
    )
    for commune in communes_qs:
        commune.code_insee = commune.nouvelle_code_insee
    Commune.objects.bulk_update(communes_qs, fields=["code_insee"])


def erase_code_insee(apps, schema_editor) -> None:  # noqa: ANN001, ARG001
    Commune = apps.get_model("core", "Commune")
    Commune.objects.update(code_insee="")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_event_types_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectivite",
            name="code_insee",
            field=models.CharField(blank=True, max_length=7, verbose_name="code INSEE"),
        ),
        migrations.RunPython(fill_code_insee, reverse_code=erase_code_insee),
    ]
