# Generated by Django 6.0.6 on 2026-07-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_collectivite_code_insee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communeprocedure",
            name="collectivite_type",
            field=models.TextField(
                choices=[
                    ("COM", "Commune"),
                    ("COMD", "Commune déléguée"),
                    ("COMA", "Commune associée"),
                    ("UNKWN", "Inconnu"),
                ],
                default="COM",
                verbose_name="Type de collectivité",
            ),
        ),
    ]
