# Generated by Django 6.0.7 on 2026-07-20 09:15

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_alter_communeprocedure_collectivite_type"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="event",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="event",
            name="update_update",
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.eventtype",
                verbose_name="type",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="event",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "history_eventsnapshot" ("code", "date_iso", "description", "event_type_id", "from_sudocuh", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "procedure_id", "profile_id", "type") VALUES (NEW."code", NEW."date_iso", NEW."description", NEW."event_type_id", NEW."from_sudocuh", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."procedure_id", NEW."profile_id", NEW."type"); RETURN NULL;',
                    hash="2705e39c888dff30f097263e258c530db13ebdb4",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_137f2",
                    table="doc_frise_events",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="event",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."code" IS DISTINCT FROM (NEW."code") OR OLD."date_iso" IS DISTINCT FROM (NEW."date_iso") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."event_type_id" IS DISTINCT FROM (NEW."event_type_id") OR OLD."from_sudocuh" IS DISTINCT FROM (NEW."from_sudocuh") OR OLD."procedure_id" IS DISTINCT FROM (NEW."procedure_id") OR OLD."profile_id" IS DISTINCT FROM (NEW."profile_id") OR OLD."type" IS DISTINCT FROM (NEW."type"))',
                    func='INSERT INTO "history_eventsnapshot" ("code", "date_iso", "description", "event_type_id", "from_sudocuh", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "procedure_id", "profile_id", "type") VALUES (NEW."code", NEW."date_iso", NEW."description", NEW."event_type_id", NEW."from_sudocuh", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."procedure_id", NEW."profile_id", NEW."type"); RETURN NULL;',
                    hash="8b017fc74fcc56002d530a0b033cd1150c03fa34",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_d4328",
                    table="doc_frise_events",
                    when="AFTER",
                ),
            ),
        ),
    ]
