# Generated by Django 6.0.7 on 2026-07-21 13:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_event_add_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtype",
            name="scope_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("pp", "Procédure principale"),
                        ("ppi", "Procédure principale intercommunale"),
                        ("rms", "Révision allégée ou à modalité simplifiée"),
                        ("m", "Modification (antérieur loi Huwart)"),
                        ("ms", "Modification simplifiée"),
                        ("mc", "Mise en compatibilité"),
                        ("mj", "Mise à jour"),
                        ("mlh", "Modification (postérieur loi Huwart)"),
                        ("pplh", "Procédure principale (postérieur loi Huwart)"),
                        (
                            "ppilh",
                            "Procédure principale intercommunale (postérieur loi Huwart)",
                        ),
                    ]
                ),
                blank=True,
                db_default="{}",
                default=list,
                verbose_name="liste des scopes",
            ),
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="scope_sugg",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("pp", "Procédure principale"),
                        ("ppi", "Procédure principale intercommunale"),
                        ("rms", "Révision allégée ou à modalité simplifiée"),
                        ("m", "Modification (antérieur loi Huwart)"),
                        ("ms", "Modification simplifiée"),
                        ("mc", "Mise en compatibilité"),
                        ("mj", "Mise à jour"),
                        ("mlh", "Modification (postérieur loi Huwart)"),
                        ("pplh", "Procédure principale (postérieur loi Huwart)"),
                        (
                            "ppilh",
                            "Procédure principale intercommunale (postérieur loi Huwart)",
                        ),
                    ]
                ),
                blank=True,
                db_default="{}",
                default=list,
                verbose_name="Scopes suggérés",
            ),
        ),
    ]
