# Generated by Django 6.0.7 on 2026-07-21 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_alter_eventtype_scope_list_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="actors",
        ),
        migrations.RemoveField(
            model_name="event",
            name="is_sudocuh_scot",
        ),
        migrations.RemoveField(
            model_name="event",
            name="test",
        ),
    ]
