# Generated by Django 6.0.7 on 2026-07-21 15:16

import django.db.models.deletion
from django.db import migrations, models


def delete_event_without_procedure(apps, schema_editor) -> None:  # noqa: ANN001, ARG001
    Event = apps.get_model("core", "Event")
    Event.objects.filter(procedure__isnull=True).delete()


DISABLE_TRIGGERS = "ALTER TABLE doc_frise_events DISABLE TRIGGER USER"

ENABLE_TRIGGERS = "ALTER TABLE doc_frise_events ENABLE TRIGGER USER"


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_remove_event_unused_fields"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DISABLE_TRIGGERS, reverse_sql=ENABLE_TRIGGERS, elidable=True
        ),
        migrations.RunPython(
            delete_event_without_procedure,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.RunSQL(
            sql=ENABLE_TRIGGERS, reverse_sql=DISABLE_TRIGGERS, elidable=True
        ),
        migrations.AlterField(
            model_name="event",
            name="procedure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.procedure",
                verbose_name="procédure",
            ),
        ),
    ]
