# Generated by Django 6.0.7 on 2026-07-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_alter_event_procedure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedure",
            name="is_principale",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="procedure",
            name="type",
            field=models.CharField(
                choices=[
                    ("Abrogation", "Abrogation"),
                    ("Elaboration", "Elaboration"),
                    ("Mise à jour", "Mise à jour"),
                    ("Mise en compatibilité", "Mise en compatibilité"),
                    ("Modification", "Modification"),
                    ("Modification simplifiée", "Modification simplifiée"),
                    ("Révision", "Révision"),
                    (
                        "Révision à modalité simplifiée ou Révision allégée",
                        "Révision à modalité simplifiée ou Révision allégée",
                    ),
                    ("Révision allégée (ou RMS)", "Révision allégée (ou RMS)"),
                    ("Révision simplifiée", "Révision simplifiée"),
                ],
                default="Elaboration",
            ),
        ),
        migrations.AlterField(
            model_name="procedure",
            name="vaut_PDM",
            field=models.BooleanField(db_column="is_pdu", default=False),
        ),
        migrations.AlterField(
            model_name="procedure",
            name="vaut_PLH",
            field=models.BooleanField(db_column="is_pluih", default=False),
        ),
        migrations.AlterField(
            model_name="procedure",
            name="vaut_SCoT",
            field=models.BooleanField(db_column="is_scot", default=False),
        ),
    ]
