# Generated by Django 6.0.7 on 2026-07-31 13:58

from django.db import migrations


def update_procedure_vaut_PDM(apps, schema_editor) -> None:  # noqa: ANN001, ARG001, N802
    Procedure = apps.get_model("core", "Procedure")
    # Fill procedure.is_pdu
    # select count(*) from procedures p
    # where p.is_pdu is false;
    # => 165844
    # --
    # select count(*) from procedures p
    # where p.is_pdu is false and p.from_sudocuh is null
    # => 3
    # select count(*) from procedures p
    # where p.is_pdu is null;
    # => 7522
    # select count(*) from procedures p
    # where p.is_pdu is null and p.from_sudocuh is not null;
    # => 1188
    # BUT it's set to null automatically on procedure creation. I don't know why.
    Procedure.objects.filter(vaut_PDM__isnull=True).update(vaut_PDM=False)


def update_procedure_vaut_PLH(apps, schema_editor) -> None:  # noqa: ANN001, ARG001, N802
    Procedure = apps.get_model("core", "Procedure")
    # select count(*) from procedures p
    # where p.is_pluih is not true and p.doc_type = 'PLUiH';
    # => 2
    Procedure.objects.filter(doc_type="PLUiH").exclude(vaut_PLH=True).update(
        vaut_PLH=True
    )
    # select count(*) from procedures p
    # where p.is_pluih is true and p.doc_type != 'PLUiH';
    # => 372
    # select distinct p.doc_type from procedures p
    # where p.is_pluih is true and p.doc_type != 'PLUiH';
    # => PLU, PLUi, PLUiHM
    Procedure.objects.exclude(doc_type="PLUiH").filter(vaut_PLH=True).update(
        vaut_PLH=False
    )


def update_procedure_vaut_SCoT(apps, schema_editor) -> None:  # noqa: ANN001, ARG001, N802
    Procedure = apps.get_model("core", "Procedure")
    # select count(*) from procedures p
    #  where p.is_scot is not true and p.doc_type = 'SCOT';
    # => 220
    Procedure.objects.filter(doc_type="SCOT").exclude(vaut_SCoT=True).update(
        vaut_SCoT=True
    )
    # select count(*) from procedures p
    # where p.is_scot is true and p.doc_type != 'SCOT';
    # => 86
    # select distinct p.doc_type from procedures p
    #  where p.is_scot is true and p.doc_type != 'SCOT';
    # => PLU, PLUi, POS, SD
    Procedure.objects.exclude(doc_type="SCOT").filter(vaut_SCoT=True).update(
        vaut_SCoT=False
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_alter_procedure_is_principale_alter_procedure_type_and_more"),
    ]

    operations = [
        migrations.RunPython(
            update_procedure_vaut_PDM,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.RunPython(
            update_procedure_vaut_PLH,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.RunPython(
            update_procedure_vaut_SCoT,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
