# Generated by Django 6.0.7 on 2026-08-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_alter_event_event_type_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedure",
            name="vaut_PDM",
            field=models.BooleanField(
                blank=True, db_column="is_pdu", null=True, verbose_name="is_pdu"
            ),
        ),
        migrations.AlterField(
            model_name="procedure",
            name="vaut_PLH",
            field=models.BooleanField(
                blank=True, db_column="is_pluih", null=True, verbose_name="is_pluih"
            ),
        ),
        migrations.AlterField(
            model_name="procedure",
            name="vaut_SCoT",
            field=models.BooleanField(
                blank=True, db_column="is_scot", null=True, verbose_name="is_scot"
            ),
        ),
    ]
