# Generated by Django 6.0.6 on 2026-06-18 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_alter_event_event_type_blank"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP FUNCTION IF EXISTS public.get_event_status;
                """,
            reverse_sql="""
                CREATE FUNCTION public.get_event_status(p_id uuid, doc_type text) RETURNS text
                    LANGUAGE plpgsql
                    AS $$
                DECLARE
                    event_record doc_frise_events%ROWTYPE;
                    new_status TEXT;
                    current_date_opposable DATE;
                BEGIN
                    FOR event_record IN
                        SELECT *
                        FROM doc_frise_events
                        WHERE procedure_id = p_id
                        AND (is_valid = true OR type = 'Abandon')
                        ORDER BY date_iso DESC, type
                    LOOP
                        new_status := get_event_impact(event_record, doc_type);

                        IF new_status = 'opposable' THEN
                            current_date_opposable := event_record.date_iso;
                        END IF;

                        IF new_status IS NOT NULL THEN
                            EXIT;
                        END IF;
                    END LOOP;

                    IF new_status IS NULL THEN
                        new_status := 'en cours';
                    END IF;

                    RETURN new_status;
                END $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DROP FUNCTION IF EXISTS public.one_shot_events;
            """,
            reverse_sql="""
                CREATE FUNCTION public.one_shot_events() RETURNS void
                    LANGUAGE plpgsql
                    AS $$
                DECLARE
                    procedure procedures;
                    start_time timestamp := clock_timestamp();
                    end_time timestamp;
                    execution_time interval;
                    i INT := 0;
                BEGIN
                    RAISE LOG 'Processing One shot events';
                    UPDATE procedures SET status = null;
                    FOR procedure IN SELECT * FROM procedures WHERE is_principale IS TRUE LOOP i := i + 1;
                        RAISE LOG 'Processing procedure events N: %', i;
                        PERFORM set_procedure_status(procedure);
                    END LOOP;
                    end_time := clock_timestamp();
                    execution_time := end_time - start_time;
                    RAISE LOG 'FUNCTION ONE SHOT execution time: %', execution_time;
                END; $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DROP FUNCTION IF EXISTS public.procedure_status_handler;
            """,
            reverse_sql="""
                CREATE FUNCTION public.procedure_status_handler() RETURNS trigger
                    LANGUAGE plpgsql
                    AS $$
                DECLARE
                    procedure procedures;
                BEGIN
                    IF TG_OP = 'UPDATE' OR TG_OP = 'INSERT' then
                        procedure := new;
                    else
                        procedure := old;
                    END IF;

                    PERFORM set_procedure_status(procedure);

                    -- Perform the HTTP GET request
                    -- TODO(cms): API call is disabled here because Nuxt3 does not listen on test mode.
                    -- PERFORM http_get('localhost:4000/api/urba/procedures/' || procedure.id || '/update');
                    return procedure;
                END;
                $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DROP FUNCTION IF EXISTS public.perimetre_by_procedures_ids_and_insee_codes;
            """,
            reverse_sql="""
                CREATE FUNCTION public.perimetre_by_procedures_ids_and_insee_codes(procedures_ids json, insee_codes json) RETURNS void
                LANGUAGE sql
                AS $$
                    UPDATE procedures_perimetres
                    SET opposable = true
                    WHERE procedure_id::text IN (SELECT value FROM jsonb_array_elements_text(procedures_ids::jsonb))
                    AND collectivite_code::text IN (SELECT value FROM jsonb_array_elements_text(insee_codes::jsonb))
                $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DROP FUNCTION IF EXISTS public.procedures_by_insee_codes;
            """,
            reverse_sql="""
                CREATE FUNCTION public.procedures_by_insee_codes(codes json) RETURNS SETOF record
                    LANGUAGE sql
                    AS $$
                SELECT *
                FROM procedures
                WHERE EXISTS (
                SELECT id, status, doc_type, current_perimetre, is_pluih
                FROM jsonb_array_elements(current_perimetre) obj
                WHERE ((obj->>'inseeCode')::text IN (
                    SELECT jsonb_array_elements_text(codes::jsonb)
                )) and (status in ('opposable', 'en cours')) and (is_principale = true)
                );
                $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DROP FUNCTION IF EXISTS public.procedures_by_sudocuh_ids;
            """,
            reverse_sql="""
                CREATE FUNCTION public.procedures_by_sudocuh_ids(sudocuh_ids json) RETURNS SETOF record
                    LANGUAGE sql
                    AS $$
                SELECT id, from_sudocuh, initial_perimetre, current_perimetre, status
                FROM procedures
                WHERE from_sudocuh::text IN (SELECT value FROM jsonb_array_elements_text(sudocuh_ids::jsonb));
                $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DROP FUNCTION IF EXISTS public.events_by_procedures_ids;
            """,
            reverse_sql="""
                CREATE FUNCTION public.events_by_procedures_ids(procedures_ids json) RETURNS SETOF record
                    LANGUAGE sql
                    AS $$
                SELECT *
                FROM doc_frise_events
                WHERE procedure_id::text IN (SELECT value FROM jsonb_array_elements_text(procedures_ids::jsonb));
                $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DROP FUNCTION IF EXISTS public.procedures_principales_by_collectivites;
            """,
            reverse_sql="""
                CREATE FUNCTION public.procedures_principales_by_collectivites(codes json)
                    RETURNS SETOF record
                    LANGUAGE sql
                AS $$
                    SELECT p.*, array_agg(pp.*) AS procedures_perimetres
                    FROM procedures p
                    LEFT JOIN procedures_perimetres pp ON p.id = pp.procedure_id
                    WHERE ((p.id IN (
                        SELECT procedure_id
                        FROM procedures_perimetres
                        WHERE collectivite_code IN (
                            SELECT json_array_elements_text(codes)
                        )
                    )) AND p.is_principale = true AND p.status IN ('opposable', 'en cours')) GROUP BY p.id;
                $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DROP FUNCTION IF EXISTS public.validated_collectivites;
            """,
            reverse_sql="""
                CREATE OR REPLACE FUNCTION public.validated_collectivites(since date, departement text)
                RETURNS TABLE (
                    collectivite_code text,
                    created_at timestamp,
                    profile_id uuid,
                    email text
                )
                LANGUAGE sql
                AS $$
                SELECT
                    inn.*,
                    pf.email
                FROM
                    (
                        SELECT
                            pv.collectivite_code,
                            MIN(pv.created_at) AS created_at,
                            MIN(pv.profile_id::text)::UUID AS profile_id
                        FROM
                            procedures_validations pv
                        WHERE
                            pv.created_at > since
                            AND pv.departement = departement
                        GROUP BY
                            pv.collectivite_code
                        ORDER BY
                            pv.collectivite_code
                    ) AS inn
                    LEFT JOIN profiles pf ON inn.profile_id = pf.user_id;
                $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DROP FUNCTION IF EXISTS public.validated_collectivites_by_depts;
            """,
            reverse_sql="""
                CREATE OR REPLACE FUNCTION public.validated_collectivites_by_depts(since date)
                RETURNS TABLE (
                    departement text,
                    unique_collectivites_count bigint
                )
                LANGUAGE sql
                SECURITY DEFINER
                AS $$
                SELECT
                    departement,
                    COUNT(DISTINCT collectivite_code) AS unique_collectivites_count
                FROM
                    procedures_validations
                WHERE
                created_at > since
                GROUP BY
                    departement
                ORDER BY
                    departement;
                $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DROP TRIGGER IF EXISTS handle_updated_at ON public.doc_frise_events;
            """,
            reverse_sql="""
                create extension if not exists moddatetime schema extensions;
                CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.doc_frise_events FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');
            """,
        ),
    ]
