# Generated by Django 6.0.6 on 2026-06-18 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_remove_sql_unused_functions"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP TRIGGER IF EXISTS trigger_event_procedure_status_handler ON public.doc_frise_events;
            """,
            reverse_sql="""
                CREATE TRIGGER trigger_event_procedure_status_handler AFTER INSERT OR DELETE OR UPDATE ON public.doc_frise_events FOR EACH ROW EXECUTE FUNCTION public.event_procedure_status_handler();
            """,
        ),
        migrations.RunSQL(
            sql="""
                DROP FUNCTION IF EXISTS public.event_procedure_status_handler;
                """,
            reverse_sql="""
                CREATE FUNCTION public.event_procedure_status_handler() RETURNS trigger
                    LANGUAGE plpgsql
                    AS $$ declare procedure procedures; event_processed doc_frise_events;
                    BEGIN
                        IF TG_OP = 'UPDATE' OR TG_OP = 'INSERT' then event_processed := new;
                        else event_processed := old;
                        END IF;
                        SELECT * into procedure FROM procedures WHERE id = event_processed.procedure_id;
                        PERFORM set_procedure_status(procedure);
                        /* NUXT3_API_URL is hardcoded here because this dump will disappear soon and I don't know how to change it quickly in SQL. */
                        PERFORM net.http_get('http://localhost:4000/api/urba/procedures/' || event_processed.procedure_id || '/update');
                    return event_processed; END; $$;
            """,
        ),
        migrations.RunSQL(
            sql="""
                DROP FUNCTION IF EXISTS public.set_procedure_status;
                """,
            reverse_sql="""
                CREATE FUNCTION public.set_procedure_status(procedure public.procedures) RETURNS void
                    LANGUAGE plpgsql
                    AS $$ DECLARE new_status text; event doc_frise_events; current_date_opposable text; BEGIN FOR event IN SELECT * FROM doc_frise_events WHERE procedure_id = procedure.id AND (is_valid = true OR type = 'Abandon') ORDER BY date_iso DESC, type LOOP new_status := get_event_impact(event, procedure.doc_type); IF new_status = 'opposable' THEN current_date_opposable := event.date_iso; END IF; IF new_status IS NOT null then EXIT; END IF; END LOOP; IF new_status IS NULL THEN new_status := 'en cours'; END IF; UPDATE procedures SET status = new_status WHERE id = procedure.id; current_date_opposable := null; new_status := null; END; $$;
                """,
        ),
        migrations.RunSQL(
            sql="""
                DROP FUNCTION IF EXISTS public.get_event_impact;
                """,
            reverse_sql="""
                CREATE FUNCTION public.get_event_impact(event_processed public.doc_frise_events, doc_type text) RETURNS text
                    LANGUAGE plpgsql
                    AS $$ declare is_opposable_event bool; is_caduc_event bool; is_abandon_event bool; is_ongoing_event bool; is_annule_event bool; new_status text := NULL; impactful_events jsonb := '{ "CC": { "en cours": ["Délibération de prescription du conseil municipal"], "opposable": ["Approbation du préfet", "Caractère exécutoire", "Retrait de l''annulation totale"], "abandon": ["Abandon", "Retrait de la délibération de prescription"], "annule": ["Annulation TA totale", "Annulation TA", "Abrogation effective"], "caduc": [] }, "SCOT": { "en cours": ["Délibération de l''établissement public qui prescrit", "Retrait de la délibération d''approbation"], "opposable": ["Délibération d''approbation", "Caractère exécutoire", "Retrait de l''annulation totale"], "abandon": ["Abandon", "Retrait de la délibération de prescription"], "annule": ["Annulation TA totale", "Annulation TA"], "caduc": ["Caducité"] }, "SD": { "en cours": ["Délibération de l''établissement public qui prescrit"], "opposable": ["Délibération d''approbation", "Caractère exécutoire"], "abandon": ["Abandon"], "annule": ["Annulation TA totale", "Annulation TA"], "caduc": ["Caducité"] }, "PLU": { "en cours": ["Délibération de prescription du conseil municipal ou communautaire"], "opposable": ["Caractère exécutoire", "Retrait de l''annulation totale", "Délibération d''approbation du municipal ou communautaire", "Délibération d''approbation du conseil municipal ou communautaire", "Délibération d''approbation"], "abandon": ["Abandon", "Retrait de la délibération de prescription"], "annule": ["Annulation TA totale", "Annulation TA", "Abrogation", "Arrêté d''abrogation"], "caduc": ["Caducité"] }, "POS": { "en cours": ["Délibération de prescription du conseil municipal ou communautaire"], "opposable": ["Caractère exécutoire", "Délibération d''approbation du municipal ou communautaire", "Délibération d''approbation du conseil municipal ou communautaire", "Délibération d''approbation"], "abandon": ["Abandon"], "annule": ["Annulation TA", "Annulation TA totale", "Caducité"], "caduc": [] } }'; begin if doc_type ILIKE 'PLU%' then doc_type := 'PLU'; end if; RAISE LOG 'doc_type PASSED IN FUNC: %', doc_type; select (impactful_events->doc_type->'caduc')::jsonb ? event_processed.type into is_caduc_event; if is_caduc_event is true then RAISE LOG 'IS CADUC: %', event_processed.type; return 'caduc'; end if; select (impactful_events->doc_type->'opposable')::jsonb ? event_processed.type into is_opposable_event; if is_opposable_event is true then RAISE LOG 'IS OPPOSABLE: %', event_processed.type; return 'opposable'; end if; select (impactful_events->doc_type->'annule')::jsonb ? event_processed.type into is_annule_event; if is_annule_event is true then RAISE LOG 'IS ANNULE'; return 'annule'; end if; select (impactful_events->doc_type->'en cours')::jsonb ? event_processed.type into is_ongoing_event; if is_ongoing_event is true then RAISE LOG 'IS EN COURS'; return 'en cours'; end if; select (impactful_events->doc_type->'abandon')::jsonb ? event_processed.type into is_abandon_event; if is_abandon_event is true then RAISE LOG 'IS ABANDON'; return 'abandon'; end if; return null; end; $$;
            """,
        ),
    ]
