# Generated by Django 6.0.7 on 2026-07-31 13:58

from django.db import migrations


def update_procedure_vaut_PDM(apps, schema_editor) -> None:  # noqa: ANN001, ARG001, N802
    Procedure = apps.get_model("core", "Procedure")
    Procedure.objects.filter(vaut_PDM__isnull=True).update(vaut_PDM=False)
    Procedure.objects.filter(
        doc_type__in=["PLUiM", "PLUiHM", "PLUiMS"], vaut_PDM=False
    ).update(vaut_PDM=True)
    Procedure.objects.exclude(doc_type__in=["PLUiM", "PLUiHM", "PLUiMS"]).filter(
        vaut_PDM=True
    ).update(vaut_PDM=False)


def update_procedure_vaut_PLH(apps, schema_editor) -> None:  # noqa: ANN001, ARG001, N802
    Procedure = apps.get_model("core", "Procedure")
    Procedure.objects.filter(vaut_PLH__isnull=True).update(vaut_PLH=False)
    Procedure.objects.filter(
        doc_type__in=["PLUiH", "PLUiHM", "PLUiSH", "PLUiSHM"], vaut_PLH=False
    ).update(vaut_PLH=True)
    Procedure.objects.exclude(
        doc_type__in=["PLUiH", "PLUiHM", "PLUiSH", "PLUiSHM"]
    ).filter(vaut_PLH=True).update(vaut_PLH=False)


def update_procedure_vaut_SCoT(apps, schema_editor) -> None:  # noqa: ANN001, ARG001, N802
    Procedure = apps.get_model("core", "Procedure")
    Procedure.objects.filter(vaut_SCoT__isnull=True).update(vaut_SCoT=False)
    Procedure.objects.filter(doc_type__in=["SCOT", "SD"], vaut_SCoT=False).update(
        vaut_SCoT=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_alter_procedure_is_principale_alter_procedure_type_and_more"),
    ]

    operations = [
        migrations.RunPython(
            update_procedure_vaut_PDM,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.RunPython(
            update_procedure_vaut_PLH,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.RunPython(
            update_procedure_vaut_SCoT,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
