# Generated by Django 6.1.1 on 2026-09-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_remove_procedure_status_functions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsharing",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("write_frise", "Écriture frise"),
                    ("write", "Écriture"),
                    ("read", "Lecture"),
                ],
                db_default="read",
                default="read",
                verbose_name="rôle",
            ),
        ),
    ]
