# Generated by Django 6.0.8 on 2026-08-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_remove_procedure_status_functions"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedure",
            name="name_complement",
            field=models.CharField(
                blank=True, db_default="", default="", verbose_name="complément du nom"
            ),
        ),
    ]
