# Generated by Django 6.0.7 on 2026-07-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_fill_procedure_is_pdu_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedure",
            name="shareable",
            field=models.BooleanField(db_default=True),
        ),
    ]
