# Generated by Django 6.1.1 on 2026-10-09 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_procedure_name_complement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communeprocedure",
            name="commune",
            field=models.ForeignObject(
                from_fields=("commune_id",),
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="procedures_through",
                to="core.commune",
                to_fields=("collectivite_ptr_id",),
            ),
        ),
    ]
