# Generated by Django 6.0.7 on 2026-07-31 13:58

from django.db import migrations, models


# is_pdu
def update_procedure_vaut_PDM(apps, schema_editor) -> None:  # noqa: ANN001, ARG001, N802
    # - toutes les procédures qui ont un doc_type PLUiM, PLUiHM, PLUiMS doivent avoir is_pdu = *true* , sinon = *false*
    Procedure = apps.get_model("core", "Procedure")
    query = models.Q(doc_type__in=["PLUiM", "PLUiHM", "PLUiMS"])
    Procedure.objects.filter(query).update(vaut_PDM=True)
    Procedure.objects.exclude(query).update(vaut_PDM=False)


# is_pluih
def update_procedure_vaut_PLH(apps, schema_editor) -> None:  # noqa: ANN001, ARG001, N802
    # - toutes les procédures qui ont un doc_type PLUiH, PLUiHM, PLUiSH, PLUiSHM ont is_pluih = true, sinon false
    Procedure = apps.get_model("core", "Procedure")
    query = models.Q(doc_type__in=["PLUiH", "PLUiHM", "PLUiSH", "PLUiSHM"])
    Procedure.objects.filter(query).update(vaut_PLH=True)
    Procedure.objects.exclude(query).update(vaut_PLH=False)


# is_scot
def update_procedure_vaut_SCoT(apps, schema_editor) -> None:  # noqa: ANN001, ARG001, N802
    # - toutes les procédures qui ont doc_type = SD ou SCoT ont is_scot = true, sinon = *false* **sauf pour l'historique Sudocuh** *=*⚠️ is_scot peut être true même si  doc_type ≠ SD ou SCoT si et uniquement si from sudocuh = oui ⚠️
    # Docurba procedures
    Procedure = apps.get_model("core", "Procedure")
    Procedure.objects.filter(
        models.Q(from_sudocuh__isnull=True) & models.Q(doc_type__in=["SD", "SCOT"])
    ).update(vaut_SCoT=True)  # 195
    Procedure.objects.filter(from_sudocuh__isnull=True).exclude(
        models.Q(doc_type__in=["SD", "SCOT"])
    ).update(vaut_SCoT=False)  # 1081
    # Sudocuh procedures
    Procedure.objects.exclude(from_sudocuh__isnull=True).filter(
        models.Q(vaut_SCoT__isnull=True) & models.Q(doc_type__in=["SD", "SCOT"])
    ).update(vaut_SCoT=True)  # 95
    Procedure.objects.exclude(from_sudocuh__isnull=True).filter(
        models.Q(vaut_SCoT__isnull=True) & ~models.Q(doc_type__in=["SD", "SCOT"])
    ).update(vaut_SCoT=False)  # 18
    # TODO: test me
    # assert Procedure.objects.filter(vaut_SCoT__isnull=True).count() == 0


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_procedure_name_complement"),
    ]

    operations = [
        migrations.RunPython(
            update_procedure_vaut_PDM,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.RunPython(
            update_procedure_vaut_PLH,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.RunPython(
            update_procedure_vaut_SCoT,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
