# Generated by Django 6.0.3 on 2026-03-30 09:30

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0018_add_last_updated_by_id_to_procedures"),
        ("users", "0002_add_column_departements"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcedureSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(null=True, verbose_name="répondu le"),
                ),
                (
                    "departements",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=20),
                        blank=True,
                        null=True,
                        verbose_name="Départements de la collectivité porteuse",
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(
                        db_default=False, null=True, verbose_name="est validée"
                    ),
                ),
                (
                    "collectivite_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.collectivite",
                        to_field="code_insee_unique",
                        verbose_name="collectivité",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys_answers",
                        to="core.procedure",
                        verbose_name="procédure",
                    ),
                ),
                (
                    "respondant",
                    models.ForeignKey(
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="surveys_answers",
                        to="users.profile",
                        verbose_name="répondant",
                    ),
                ),
            ],
            options={
                "verbose_name": "validation",
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True, verbose_name="nom unique")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créée le"),
                ),
                (
                    "procedures",
                    models.ManyToManyField(
                        related_name="surveys",
                        through="surveys.ProcedureSurvey",
                        to="core.procedure",
                        verbose_name="procédures",
                    ),
                ),
            ],
            options={
                "verbose_name": "enquête",
            },
        ),
        migrations.AddField(
            model_name="proceduresurvey",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="procedures_through",
                to="surveys.survey",
                verbose_name="enquête",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="proceduresurvey",
            unique_together={("procedure", "survey")},
        ),
    ]
