# Generated by Django 6.0.2 on 2026-03-05 14:19

from django.db import migrations


def enable_rls(table_name: str) -> str:
    return f'alter table "{table_name}" enable row level security;'


def disable_rls(table_name: str) -> str:
    return f'alter table "{table_name}" disable row level security;'


def create_policy_auth_users_can_read_table(table_name: str) -> str:
    return f"""
        create policy "auth_users_can_read_{table_name}"
        on "public"."{table_name}"
        as PERMISSIVE
        for SELECT
        to authenticated
        using ( true );
    """


def drop_policy(policy_name: str, table_name: str) -> str:
    return f"drop policy if exists {policy_name} on {table_name}"


# https://supabase.com/docs/guides/getting-started/ai-prompts/database-rls-policies
def create_policy_auth_users_can_update_table_surveys_proceduresurvey() -> str:
    return """
        create policy "auth_users_can_update_table_surveys_proceduresurvey"
        on "public"."surveys_proceduresurvey"
        as PERMISSIVE
        for UPDATE
        to authenticated
        using (
            (select auth.uid() in (
                select profiles.user_id
                from profiles
                where (profiles.poste = 'ddt'))
            )
        )
        ;
    """


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=enable_rls(table_name="surveys_survey"),
            reverse_sql=disable_rls(table_name="surveys_survey"),
        ),
        migrations.RunSQL(
            sql=enable_rls(table_name="surveys_proceduresurvey"),
            reverse_sql=disable_rls(table_name="surveys_proceduresurvey"),
        ),
        migrations.RunSQL(
            sql=create_policy_auth_users_can_read_table("surveys_survey"),
            reverse_sql=drop_policy(
                "auth_users_can_read_surveys_survey", "surveys_survey"
            ),
        ),
        migrations.RunSQL(
            sql=create_policy_auth_users_can_read_table("surveys_proceduresurvey"),
            reverse_sql=drop_policy(
                "auth_users_can_read_surveys_proceduresurvey", "surveys_proceduresurvey"
            ),
        ),
        migrations.RunSQL(
            sql=create_policy_auth_users_can_update_table_surveys_proceduresurvey(),
            reverse_sql=drop_policy(
                "auth_users_can_update_table_surveys_proceduresurvey",
                "surveys_proceduresurvey",
            ),
        ),
    ]
