# Generated by Django 6.0.3 on 2026-03-24 10:44

from django.db import migrations

from docurba.surveys.models import Survey


def create_zan_03_2026_survey(*args, **kwargs) -> None:  # noqa: ANN002, ANN003, ARG001
    Survey.objects.create(name="zan_03_2026")


def delete_zan_03_2026_survey(*args, **kwargs) -> None:  # noqa: ANN002, ANN003, ARG001
    Survey.objects.get(name="zan_03_2026").delete()


# https://metabase.docurba.beta.gouv.fr/question/514-module-enquete-zan-modifications-simplifiees-de-scot-avec-un-1er-evenement-26-08-2020?departement_filter=&procedure_id_filter=
SCOTS_WITH_FIRST_EVENT_SQL = r"""
        with results as (
            select
            procedures.collectivite_porteuse_id AS "collectivite_code_id",
            procedures.id AS "procedure_id",
            departements_agreges.departements as "departements",
            surveys.id as "survey_id"
            FROM
            PROCEDURES
            LEFT JOIN (
                SELECT
                procedures_perimetres.procedure_id,
                array_agg(DISTINCT procedures_perimetres.departement) AS departements
                FROM
                procedures_perimetres
                WHERE
                procedures_perimetres.departement != '' and procedures_perimetres.departement != 'UNKWN'
                GROUP BY
                procedure_id
            ) AS departements_agreges ON PROCEDURES.id = departements_agreges.procedure_id
            -- On récupère la date du TOUT PREMIER événement (le plus ancien)
            LEFT JOIN (
            SELECT
                procedure_id,
                MIN(doc_frise_events.date_iso) AS date_premier_event
            FROM doc_frise_events
            WHERE doc_frise_events.is_valid = TRUE
            GROUP BY procedure_id
            ) AS premier_evenement ON premier_evenement.procedure_id = procedures.id
            LEFT JOIN core_collectivite ON procedures.collectivite_porteuse_id = core_collectivite.code_insee_unique,
            surveys_survey as surveys
            WHERE
            PROCEDURES.archived = FALSE
            AND procedures.type = 'Modification simplifiée'
            AND procedures.doc_type IN ('SCOT')
            -- Cas 1 : le premier événement doit être après le 22 août 2020 donc 1 an avant la loi C&R
            AND (
            (premier_evenement.date_premier_event > '2020-08-22')
            OR
                -- ou Cas 2 : Elle n'a ABSOLUMENT AUCUN événement ET elle a été créée après le 22/08/2020 : pour cela je dois utiliser last_updated_at car il y a trop de procédures sans created_at
            (procedures.last_updated_at > '2020-08-22'
            AND NOT EXISTS (
                SELECT 1
                FROM doc_frise_events
                WHERE doc_frise_events.procedure_id = PROCEDURES.id
                AND doc_frise_events.is_valid = TRUE
            )
            )
            )
            and surveys.name = 'zan_03_2026'
            and exists(
                select 1 from core_collectivite where core_collectivite.code_insee_unique = procedures.collectivite_porteuse_id
            )
        )
        insert into surveys_proceduresurvey (collectivite_code_id, procedure_id, survey_id, created_at, departements)
        select collectivite_code_id, procedure_id, survey_id, current_timestamp, departements
        from results;
"""

# https://metabase.docurba.beta.gouv.fr/question/513-module-enquete-zan-modifications-simplifiees-hors-scot-avec-un-1er-evenement-26-08-2020?departement_filter=&procedure_id_filter=
NO_SCOTS_WITH_FIRST_EVENT_SQL = r"""
        with results as (
            select
            procedures.collectivite_porteuse_id AS "collectivite_code_id",
            procedures.id AS "procedure_id",
            departements_agreges.departements as "departements",
            surveys.id as "survey_id"
            FROM
            PROCEDURES
            LEFT JOIN (
                SELECT
                procedures_perimetres.procedure_id,
                array_agg(DISTINCT procedures_perimetres.departement) AS departements
                FROM
                procedures_perimetres
                WHERE
                procedures_perimetres.departement != '' and procedures_perimetres.departement != 'UNKWN'
                GROUP BY
                procedure_id
            ) AS departements_agreges ON PROCEDURES.id = departements_agreges.procedure_id
            -- On récupère la date du TOUT PREMIER événement (le plus ancien)
            LEFT JOIN (
            SELECT
                procedure_id,
                MIN(doc_frise_events.date_iso) AS date_premier_event
            FROM doc_frise_events
            WHERE doc_frise_events.is_valid = TRUE
            GROUP BY procedure_id
            ) AS premier_evenement ON premier_evenement.procedure_id = procedures.id
            LEFT JOIN core_collectivite ON procedures.collectivite_porteuse_id = core_collectivite.code_insee_unique,
            surveys_survey as surveys
            WHERE
            PROCEDURES.archived = FALSE
            AND procedures.type = 'Modification simplifiée'
            AND procedures.doc_type NOT IN ('SCOT')
            -- Cas 1 : le premier événement doit être après le 22 août 2020
            AND (
            (premier_evenement.date_premier_event > '2020-08-22')
            OR
                -- ou Cas 2 : Elle n'a ABSOLUMENT AUCUN événement ET elle a été créée après le 22/08/2020 : pour cela je dois utiliser last_updated_at car il y a trop de procédures sans created_at
                (
                procedures.last_updated_at > '2020-08-22'
                AND NOT EXISTS (
                    SELECT 1
                    FROM doc_frise_events
                    WHERE doc_frise_events.procedure_id = PROCEDURES.id
                    AND doc_frise_events.is_valid = TRUE
                )
                )
                )
            and surveys.name = 'zan_03_2026'
            and exists(
                select 1 from core_collectivite where core_collectivite.code_insee_unique = procedures.collectivite_porteuse_id
            )
        )
        insert into surveys_proceduresurvey (collectivite_code_id, procedure_id, survey_id, created_at, departements)
        select collectivite_code_id, procedure_id, survey_id, current_timestamp, departements
        from results;
"""

# https://metabase.docurba.beta.gouv.fr/question/520-module-enquete-zan-procedures-principales-hors-scot-en-cours-ou-opposables-en-retirant-le-statut-precedent-sans-date-approbation-26-08-2021-et-sans-date-arret-26-08-2021?departement_filter=&procedure_id_filter=
ONGOING_OR_ENFORCEABLE = r"""
        with results as (
            select
            procedures.collectivite_porteuse_id AS "collectivite_code_id",
            procedures.id AS "procedure_id",
            departements_agreges.departements as "departements",
            surveys.id as "survey_id"
            FROM
            PROCEDURES
            LEFT JOIN (
                SELECT
                procedures_perimetres.procedure_id,
                array_agg(DISTINCT procedures_perimetres.departement) AS departements
                FROM
                procedures_perimetres
                WHERE
                procedures_perimetres.departement != '' and procedures_perimetres.departement != 'UNKWN'
                GROUP BY
                procedure_id
            ) AS departements_agreges ON PROCEDURES.id = departements_agreges.procedure_id
            LEFT JOIN (
                SELECT
                doc_frise_events.procedure_id,
                MAX(
                    CASE
                    WHEN doc_frise_events.type ~* '\yapprobation\y' THEN doc_frise_events.date_iso
                    ELSE NULL
                    END
                ) AS date_approbation
                FROM
                doc_frise_events
                WHERE
                doc_frise_events.is_valid = TRUE
                GROUP BY
                doc_frise_events.procedure_id
            ) AS evenement_approbation ON procedures.id = evenement_approbation.procedure_id -- On définit la date d'arrêt (on regarde la plus récente si plusieurs - choix arbitraire)
            LEFT JOIN (
                SELECT
                procedure_id,
                MAX(doc_frise_events.date_iso) AS date_arret
                FROM
                doc_frise_events
                WHERE
                doc_frise_events.is_valid = TRUE
                AND doc_frise_events.type ~* 'Arrêt de projet'
                GROUP BY
                procedure_id
            ) AS evenement_arret ON evenement_arret.procedure_id = procedures.id
            LEFT JOIN core_collectivite ON procedures.collectivite_porteuse_id = core_collectivite.code_insee_unique,
            surveys_survey as surveys
            WHERE
            PROCEDURES.archived = FALSE
            AND PROCEDURES.is_principale = TRUE --AND procedures.status IN ('en cours', 'opposable')
            AND procedures.type NOT IN ('Abrogation')
            AND procedures.doc_type NOT IN ('SCOT')
            AND (
                -- soit le statut est en cours soit le statut est opposable mais dans ces cas là il faut qu'il le soit aussi dans la table perimètre pour au moins une ligne pour une même procédure_id
                PROCEDURES.STATUS = 'en cours'
                OR (
                PROCEDURES.STATUS = 'opposable'
                AND EXISTS (
                    SELECT
                    1
                    FROM
                    procedures_perimetres pp
                    WHERE
                    pp.procedure_id = PROCEDURES.id
                    AND pp.opposable = TRUE
                )
                )
            ) -- 1. Exclure les procédures avec une date_approbation < 22/08/2021
            AND (
                evenement_approbation.date_approbation > '2021-08-22'
                OR evenement_approbation.date_approbation IS NULL
            ) -- 2. Exclure les procédures si date_arret < 22/08/2021
            AND (
                evenement_arret.date_arret > '2021-08-22'
                OR evenement_arret.date_arret IS NULL
            )
            and surveys.name = 'zan_03_2026'
            and exists(
                select 1 from core_collectivite where core_collectivite.code_insee_unique = procedures.collectivite_porteuse_id
            )
        )
        insert into surveys_proceduresurvey (collectivite_code_id, procedure_id, survey_id, created_at, departements)
        select collectivite_code_id, procedure_id, survey_id, current_timestamp, departements
        from results;
"""

# https://metabase.docurba.beta.gouv.fr/question/521-module-enquete-zan-procedures-principales-scot-en-cours-ou-opposables-en-retirant-le-statut-precedent-sans-date-approbation-22-08-2021-et-sans-date-arret-22-08-2021?departement_filter=&procedure_id_filter=
SCOTS_ONGOING_OR_ENFORCEABLE = r"""
        with results as (
            select
            procedures.collectivite_porteuse_id AS "collectivite_code_id",
            procedures.id AS "procedure_id",
            departements_agreges.departements as "departements",
            surveys.id as "survey_id"
            FROM
            PROCEDURES
            LEFT JOIN (
                SELECT
                procedures_perimetres.procedure_id,
                array_agg(DISTINCT procedures_perimetres.departement) AS departements
                FROM
                procedures_perimetres
                WHERE
                procedures_perimetres.departement != '' and procedures_perimetres.departement != 'UNKWN'
                GROUP BY
                procedure_id
            ) AS departements_agreges ON PROCEDURES.id = departements_agreges.procedure_id
            LEFT JOIN (
                SELECT
                doc_frise_events.procedure_id,
                MAX(
                    CASE
                    WHEN doc_frise_events.type ~* '\yapprobation\y' THEN doc_frise_events.date_iso
                    ELSE NULL
                    END
                ) AS date_approbation
                FROM
                doc_frise_events
                WHERE
                doc_frise_events.is_valid = TRUE
                GROUP BY
                doc_frise_events.procedure_id
            ) AS evenement_approbation ON procedures.id = evenement_approbation.procedure_id -- On définit la date d'arrêt (on regarde la plus récente si plusieurs - choix arbitraire)
            LEFT JOIN (
                SELECT
                procedure_id,
                MAX(doc_frise_events.date_iso) AS date_arret
                FROM
                doc_frise_events
                WHERE
                doc_frise_events.is_valid = TRUE
                AND doc_frise_events.type ~* 'Arrêt de projet'
                GROUP BY
                procedure_id
            ) AS evenement_arret ON evenement_arret.procedure_id = procedures.id
            LEFT JOIN core_collectivite ON procedures.collectivite_porteuse_id = core_collectivite.code_insee_unique,
            surveys_survey as surveys
            WHERE
            PROCEDURES.archived = FALSE
            AND PROCEDURES.is_principale = TRUE --AND procedures.status IN ('en cours', 'opposable')
            AND procedures.type NOT IN ('Abrogation')
            AND procedures.doc_type IN ('SCOT')
            AND (
                -- soit le statut est en cours soit le statut est opposable mais dans ces cas là il faut qu'il le soit aussi dans la table perimètre pour au moins une ligne pour une même procédure_id
                PROCEDURES.STATUS = 'en cours'
                OR (
                PROCEDURES.STATUS = 'opposable'
                AND EXISTS (
                    SELECT
                    1
                    FROM
                    procedures_perimetres pp
                    WHERE
                    pp.procedure_id = PROCEDURES.id
                    AND pp.opposable = TRUE
                )
                )
            ) -- 1. Exclure les procédures avec une date_approbation < 22/08/2021
            AND (
                evenement_approbation.date_approbation > '2021-08-22'
                OR evenement_approbation.date_approbation IS NULL
            ) -- 2. Exclure les procédures si date_arret < 22/08/2021
            AND (
                evenement_arret.date_arret > '2021-08-22'
                OR evenement_arret.date_arret IS NULL
            )
            and surveys.name = 'zan_03_2026'
            and exists(
                select 1 from core_collectivite where core_collectivite.code_insee_unique = procedures.collectivite_porteuse_id
            )
        )
        insert into surveys_proceduresurvey (collectivite_code_id, procedure_id, survey_id, created_at, departements)
        select collectivite_code_id, procedure_id, survey_id, current_timestamp, departements
        from results;
"""

# 348 records
MISSING_ZAN_PROCEDURES = r"""
with results as (
  select
    p.collectivite_porteuse_id 	as "collectivite_code_id",
    p.id as "procedure_id",
    departements_agreges.departements ,
    surveys.id as "survey_id"
  from procedures p
  LEFT JOIN (
    SELECT
    procedures_perimetres.procedure_id,
    array_agg(DISTINCT procedures_perimetres.departement) AS departements
    FROM
        procedures_perimetres
    WHERE
        procedures_perimetres.departement != '' and procedures_perimetres.departement != 'UNKWN'
    GROUP BY
        procedure_id
  ) AS departements_agreges ON p.id = departements_agreges.procedure_id
  left join core_proceduretopic cp on cp.procedure_id = p.id
  inner join core_topic topic on topic.id = cp.topic_id
  left join surveys_proceduresurvey sp on sp.procedure_id = p.id,
  surveys_survey as surveys
where
  topic.name = 'zan'
  and
  sp.id is null
  and
  surveys.name = 'zan_03_2026'
  and
  exists(
	select 1 from core_collectivite where core_collectivite.code_insee_unique = p.collectivite_porteuse_id
  )
)
insert into surveys_proceduresurvey (collectivite_code_id, procedure_id, survey_id, created_at, departements)
select collectivite_code_id, procedure_id, survey_id, current_timestamp, departements
from results;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0002_survey_rls"),
    ]

    operations = [
        migrations.RunPython(
            code=create_zan_03_2026_survey,
            reverse_code=delete_zan_03_2026_survey,
            elidable=True,
        ),
        migrations.RunSQL(
            sql=SCOTS_WITH_FIRST_EVENT_SQL,
            reverse_sql="truncate surveys_proceduresurvey",
        ),
        migrations.RunSQL(
            sql=NO_SCOTS_WITH_FIRST_EVENT_SQL,
            reverse_sql="truncate surveys_proceduresurvey",
        ),
        migrations.RunSQL(
            sql=ONGOING_OR_ENFORCEABLE,
            reverse_sql="truncate surveys_proceduresurvey",
        ),
        migrations.RunSQL(
            sql=SCOTS_ONGOING_OR_ENFORCEABLE,
            reverse_sql="truncate surveys_proceduresurvey",
        ),
        migrations.RunSQL(
            sql=MISSING_ZAN_PROCEDURES,
            reverse_sql="truncate surveys_proceduresurvey",
        ),
    ]
