# Generated by Django 6.0.3 on 2026-04-03 13:29

from django.db import migrations


def delete_archived(apps, schema_editor) -> None:  # noqa: ANN001, ARG001
    ProcedureSurvey = apps.get_model("surveys", "ProcedureSurvey")
    ProcedureSurvey.objects.filter(procedure__archived=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0003_populate_proceduresurvey"),
    ]

    operations = [
        migrations.RunPython(
            delete_archived,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        )
    ]
