# https://www.supervisord.org/running.html#running-supervisord
web: supervisord --configuration=supervisord.conf

postdeploy: bin/post_deploy

# https://doc.scalingo.com/platform/app/task-scheduling/custom-clock-processes#defining-custom-clock-processes
clock: bin/clock.sh
