# https://www.supervisord.org/configuration.html

[supervisord]
nodaemon = true

[program:gunicorn]
command=gunicorn config.wsgi --bind unix:/tmp/gunicorn.sock --worker-class=gevent
priority=1
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:nginx]
# Command bin/run is provided by Nginx buildpack
command=bin/run
priority=2
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
