/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/collectivites/[collectiviteId]/_old_index': RouteRecordInfo<
      '/collectivites/[collectiviteId]/_old_index',
      '/collectivites/:collectiviteId/_old_index',
      { collectiviteId: ParamValue<true> },
      { collectiviteId: ParamValue<false> },
      | never
    >,
    '/collectivites/[collectiviteId]/[[documentTypesGroupId]]': RouteRecordInfo<
      '/collectivites/[collectiviteId]/[[documentTypesGroupId]]',
      '/collectivites/:collectiviteId/:documentTypesGroupId?',
      { collectiviteId: ParamValue<true>, documentTypesGroupId?: ParamValueZeroOrOne<true> },
      { collectiviteId: ParamValue<false>, documentTypesGroupId?: ParamValueZeroOrOne<false> },
      | never
    >,
    '/connexion/': RouteRecordInfo<
      '/connexion/',
      '/connexion',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/connexion/collectivite/': RouteRecordInfo<
      '/connexion/collectivite/',
      '/connexion/collectivite',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/connexion/collectivite/creation': RouteRecordInfo<
      '/connexion/collectivite/creation',
      '/connexion/collectivite/creation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/connexion/etat/': RouteRecordInfo<
      '/connexion/etat/',
      '/connexion/etat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/connexion/etat/creation': RouteRecordInfo<
      '/connexion/etat/creation',
      '/connexion/etat/creation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/procedures/[procedureId]/': RouteRecordInfo<
      '/procedures/[procedureId]/',
      '/procedures/:procedureId',
      { procedureId: ParamValue<true> },
      { procedureId: ParamValue<false> },
      | never
    >,
    '/tableau-de-bord/[[departementId]]': RouteRecordInfo<
      '/tableau-de-bord/[[departementId]]',
      '/tableau-de-bord/:departementId?',
      { departementId?: ParamValueZeroOrOne<true> },
      { departementId?: ParamValueZeroOrOne<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/collectivites/[collectiviteId]/_old_index.vue': {
      routes:
        | '/collectivites/[collectiviteId]/_old_index'
      views:
        | never
    }
    'src/pages/collectivites/[collectiviteId]/[[documentTypesGroupId]].vue': {
      routes:
        | '/collectivites/[collectiviteId]/[[documentTypesGroupId]]'
      views:
        | never
    }
    'src/pages/connexion/index.vue': {
      routes:
        | '/connexion/'
      views:
        | never
    }
    'src/pages/connexion/collectivite/index.vue': {
      routes:
        | '/connexion/collectivite/'
      views:
        | never
    }
    'src/pages/connexion/collectivite/creation.vue': {
      routes:
        | '/connexion/collectivite/creation'
      views:
        | never
    }
    'src/pages/connexion/etat/index.vue': {
      routes:
        | '/connexion/etat/'
      views:
        | never
    }
    'src/pages/connexion/etat/creation.vue': {
      routes:
        | '/connexion/etat/creation'
      views:
        | never
    }
    'src/pages/procedures/[procedureId]/index.vue': {
      routes:
        | '/procedures/[procedureId]/'
      views:
        | never
    }
    'src/pages/tableau-de-bord/[[departementId]].vue': {
      routes:
        | '/tableau-de-bord/[[departementId]]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
