# Generated by Django 6.0.7 on 2026-07-23 13:51

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import docurba.users.models


class Migration(migrations.Migration):
    replaces = [
        ("users", "0001_initial"),
        ("users", "0002_add_column_departements"),
        ("users", "0003_session"),
        ("users", "0004_add_encrypted_password_to_users"),
        ("users", "0005_rename_user_to_supabase_user"),
    ]

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
            ],
            options={
                "verbose_name": "utilisateur supabase",
                "verbose_name_plural": "utilisateurs supabase",
                "managed": False,
                "db_table": '"auth"."users"',
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.user",
                        verbose_name="Utilisateur",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(blank=True, null=True, verbose_name="Prénom"),
                ),
                (
                    "lastname",
                    models.CharField(blank=True, null=True, verbose_name="Nom"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "poste",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ddt", "DDT(M)/DEAL"),
                            ("dreal", "DREAL"),
                            ("region", "Région"),
                            ("be", "Bureau d'études"),
                            ("elu", "Collectivité, Élu·e"),
                            (
                                "employe_mairie",
                                "Collectivité, Technicien·ne ou employé·e",
                            ),
                            ("agence_urba", "Agence d'urbanisme"),
                            ("autre", "Autre"),
                        ],
                        null=True,
                        verbose_name="Poste",
                    ),
                ),
                (
                    "other_poste",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                (
                                    "chef_unite",
                                    "Chef·fe d'unité/de bureau/de service et adjoint·e",
                                ),
                                ("redacteur_pac", "Rédacteur·ice de PAC"),
                                (
                                    "suivi_procedures",
                                    "Chargé·e de l'accompagnement des collectivités",
                                ),
                                ("referent_sudocuh", "Référent·e Sudocuh"),
                            ],
                        ),
                        blank=True,
                        null=True,
                        verbose_name="Role(s)",
                    ),
                ),
                (
                    "departement",
                    models.CharField(blank=True, null=True, verbose_name="Département"),
                ),
                (
                    "collectivite_id",
                    models.CharField(
                        blank=True, null=True, verbose_name="Code Collectivité"
                    ),
                ),
                (
                    "tel",
                    models.CharField(blank=True, null=True, verbose_name="Téléphone"),
                ),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                (
                    "side",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("etat", "État"),
                            ("collectivite", "Collectivité"),
                            ("ppa", "PPA"),
                        ],
                        null=True,
                        verbose_name="Side",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        db_comment="Si l'utilisateur est une DREAL ou une PPA : région de son périmètre. La colonne peut être remplie pour les autres types.",
                        null=True,
                        verbose_name="Région",
                    ),
                ),
                (
                    "no_signup",
                    models.BooleanField(
                        db_comment="Si l'utilisateur passe par un depot d'acte, il est autorisé à mettre uniquement son email. Dans ce cas l'utilisateur n'a pas de compte Docurba, et no_signup sera à TRUE.",
                        default=False,
                        verbose_name="Dépôt d'actes (no_signup)",
                    ),
                ),
                (
                    "successfully_logged_once",
                    models.BooleanField(
                        default=False, verbose_name="S'est déjà connecté"
                    ),
                ),
                (
                    "optin",
                    models.BooleanField(
                        default=False, verbose_name="Est inscrit à l'infolettre"
                    ),
                ),
                (
                    "updated_pipedrive",
                    models.BooleanField(
                        default=False, verbose_name="Est mis à jour sur Pipedrive"
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        db_comment="super admin bypass",
                        default=False,
                        verbose_name="Est admin (is_admin)",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, verbose_name="Est membre (is_staff)"
                    ),
                ),
            ],
            options={
                "verbose_name": "profil",
                "db_table": "profiles",
                "managed": False,
            },
        ),
        migrations.RunSQL(
            sql=[
                "ALTER TABLE IF EXISTS public.profiles ADD COLUMN IF NOT EXISTS departements text[]"
            ],
            reverse_sql=[
                "ALTER TABLE IF EXISTS public.profiles DROP COLUMN IF EXISTS departements"
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": '"auth"."sessions"',
                "managed": False,
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="user",
                    name="encrypted_password",
                    field=models.CharField(),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="User",
            new_name="SupabaseUser",
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "auth_user",
                "verbose_name": "utilisateur django",
                "verbose_name_plural": "utilisateurs django",
            },
            managers=[
                ("objects", docurba.users.models.DjangoUserManager()),
            ],
        ),
    ]
