# Generated by Django 6.0.4 on 2026-05-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_add_column_departements"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": '"auth"."sessions"',
                "managed": False,
            },
        ),
    ]
