# Generated by Django 6.0.7 on 2026-07-30 13:58

from django.conf import settings
from django.db import migrations

from docurba.utils.enums import DocurbaEnvironment


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_enable_track_functions"),
    ]

    operations = (
        [
            migrations.RunSQL(
                sql="""alter role "authenticator" set "track_functions" to 'none'""",
                reverse_sql="""alter role "authenticator" set "track_functions" to 'pl'""",
                elidable=True,
            ),
        ]
        if settings.DOCURBA_ENVIRONMENT != DocurbaEnvironment.TEST
        else []
    )
