# Generated by Django 6.0.6 on 2026-06-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_session"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="user",
                    name="encrypted_password",
                    field=models.CharField(),
                ),
            ],
        )
    ]
