# Generated by Django 6.0.7 on 2026-07-22 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_add_encrypted_password_to_users"),
    ]

    operations = [
        migrations.RenameModel("User", "SupabaseUser"),
    ]
