# Generated by Django 6.1 on 2026-08-27 13:25

from django.db import migrations


def enable_rls(table_name: str) -> str:
    return f'alter table "{table_name}" enable row level security;'


def disable_rls(table_name: str) -> str:
    return f'alter table "{table_name}" disable row level security;'


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_disable_track_functions"),
    ]

    operations = [
        migrations.RunSQL(
            sql=enable_rls(table_name="auth_group"),
            reverse_sql=disable_rls(table_name="auth_group"),
        ),
        migrations.RunSQL(
            sql=enable_rls(table_name="auth_group_permissions"),
            reverse_sql=disable_rls(table_name="auth_group_permissions"),
        ),
        migrations.RunSQL(
            sql=enable_rls(table_name="auth_permission"),
            reverse_sql=disable_rls(table_name="auth_permission"),
        ),
        migrations.RunSQL(
            sql=enable_rls(table_name="django_admin_log"),
            reverse_sql=disable_rls(table_name="django_admin_log"),
        ),
        migrations.RunSQL(
            sql=enable_rls(table_name="users_user"),
            reverse_sql=disable_rls(table_name="users_user"),
        ),
        migrations.RunSQL(
            sql=enable_rls(table_name="users_user_groups"),
            reverse_sql=disable_rls(table_name="users_user_groups"),
        ),
        migrations.RunSQL(
            sql=enable_rls(table_name="users_user_user_permissions"),
            reverse_sql=disable_rls(table_name="users_user_user_permissions"),
        ),
    ]
