# Generated by Django 6.1 on 2026-08-27 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_enable_rls"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE IF EXISTS public.profiles ADD COLUMN must_update_password boolean DEFAULT false NOT NULL"
            ],
            reverse_sql=[
                "ALTER TABLE IF EXISTS public.profiles DROP COLUMN IF EXISTS must_update_password"
            ],
        ),
    ]
