# Generated by Django 6.0.7 on 2026-07-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_squashed_0005_rename_user_to_supabase_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="django_user",
                to="users.profile",
                to_field="user_id",
            ),
        ),
    ]
