# Generated by Django 6.1 on 2026-09-01 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_add_colum_profile_must_update_password"),
    ]

    operations = [
        migrations.RunSQL(
            """
                UPDATE public.profiles
                SET must_update_password = true
                WHERE profiles.side != 'collectivite';
""",
            reverse_sql="""
                UPDATE public.profiles
                SET must_update_password = false;
""",
        )
    ]
