# Generated by Django 6.1 on 2026-09-03 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_fill_profile_must_reset_password"),
    ]

    # Session model is unmanaged.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name="Session",
                ),
            ],
        )
    ]
