# Generated by Django 6.1 on 2026-09-08 09:12

from django.db import migrations


def drop_policy() -> str:
    return 'drop policy if exists "Users Can Insert" on public.profiles'


def create_policy_users_can_insert_profiles() -> str:
    return """
        CREATE POLICY "Users Can Insert" ON public.profiles FOR INSERT WITH CHECK (true);
    """


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_delete_session"),
    ]

    operations = [
        migrations.RunSQL(
            sql=drop_policy(),
            reverse_sql=create_policy_users_can_insert_profiles(),
        ),
    ]
