# Generated by Django 6.1.1 on 2026-09-14 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_delete_session"),
    ]

    # Keep this table just in case we need to quickly restore it.
    # We should be able to delete it when the PAC feature will be moved to Django.
    operations = [
        migrations.RunSQL(
            sql="""alter table github_ref_roles rename to old_github_ref_roles""",
            reverse_sql="""alter table old_github_ref_roles rename to github_ref_roles""",
        )
    ]
