name: Lint & Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  all:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.TEST_SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.TEST_SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@b60b5899c73b63a2d2d651b1e90db8d4c9392f51
        with:
          version: latest
      - name: Create review app
        run: supabase --project-ref ${SUPABASE_PROJECT_REF} branches create test_3 --with-data
      - name:
      - run: supabase --experimental branches get test_3 -o env >> $GITHUB_ENV
      - name: Check connection
        run: |
          psql "$POSTGRES_URL" -c 'SELECT * FROM pg_catalog.pg_tables
          WHERE schemaname != 'pg_catalog' AND schemaname != 'information_schema';'
