name: Lint & Test
on:
  push:
    branches: [main]
  pull_request:

defaults:
  run:
    working-directory: django

jobs:
  all:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: config.settings.test
      SECRET_KEY: test_secret_key
      # Default supabase URL: https://supabase.com/docs/guides/local-development/cli/getting-started?queryGroups=access-method&access-method=postgres
      DATABASE_URL: postgresql://postgres:postgres@localhost:54322/postgres
      UPSTREAM_NUXT: http://localhost:3000

    steps:
      - uses: actions/checkout@v4

      - name: 🛠️ Installation de la CLI Supabase
        uses: supabase/setup-cli@b60b5899c73b63a2d2d651b1e90db8d4c9392f51
        with:
          version: 2.60.0

      - run: supabase db start

      - uses: actions/setup-python@v5
        with:
          python-version-file: django/.python-version
      - uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
      - run: uv sync --locked --all-extras --dev --active
      - run: pytest --create-db
      - run: ruff format --diff .
      - run: ruff check --output-format=github .
      - run: python -m django makemigrations --check --dry-run --noinput || (echo "⚠ Migration manquante ⚠"; exit 1)
