name: 🕵 Création d'une recette jetable

# L'action est lancée lorsque l'étiquette « recette-jetable » est ajoutée à la PR.
on:
  pull_request:
    types: [ labeled ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number }}

env:
  BRANCH: ${{ github.head_ref }}
  PR_ID: ${{ github.event.number }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: github.event_name=='pull_request' && github.event.action == 'labeled' && github.event.label.name == 'recette-jetable'
    outputs:
      SUPABASE_REVIEW_APP_NAME: ${{ steps.config.outputs.SUPABASE_REVIEW_APP_NAME }}
      NUXT_3_REVIEW_APP_NAME: ${{ steps.config.outputs.NUXT_3_REVIEW_APP_NAME }}
      NUXT_3_URL: ${{ steps.config.outputs.NUXT_3_URL }}
      NUXT_2_REVIEW_APP_NAME: ${{ steps.config.outputs.NUXT_2_REVIEW_APP_NAME }}
      NUXT_2_URL: ${{ steps.config.outputs.NUXT_2_URL }}
      DJANGO_REVIEW_APP_NAME: ${{ steps.config.outputs.DJANGO_REVIEW_APP_NAME }}
      DJANGO_URL: ${{ steps.config.outputs.DJANGO_URL }}

    steps:
      - name: Get configuration
        id: config
        run: |
          DOMAIN=osc-fr1.scalingo.io

          NUXT_3_REVIEW_APP_NAME=docurba-nuxt3-pr${{ env.PR_ID }}
          echo "NUXT_3_REVIEW_APP_NAME=${NUXT_3_REVIEW_APP_NAME}" >> $GITHUB_OUTPUT
          echo "NUXT_3_URL=https://${NUXT_3_REVIEW_APP_NAME}.${DOMAIN}" >> $GITHUB_OUTPUT

          NUXT_2_REVIEW_APP_NAME=docurba-nuxt-demo-pr${{ env.PR_ID }}
          echo "NUXT_2_REVIEW_APP_NAME=${NUXT_2_REVIEW_APP_NAME}" >> $GITHUB_OUTPUT
          echo "NUXT_2_URL=https://${NUXT_2_REVIEW_APP_NAME}.${DOMAIN}" >> $GITHUB_OUTPUT

          DJANGO_REVIEW_APP_NAME=docurba-django-demo-pr${{ env.PR_ID }}
          echo "DJANGO_REVIEW_APP_NAME=${DJANGO_REVIEW_APP_NAME}" >> $GITHUB_OUTPUT
          echo "DJANGO_URL=https://${DJANGO_REVIEW_APP_NAME}.${DOMAIN}" >> $GITHUB_OUTPUT

          echo "SUPABASE_REVIEW_APP_NAME=supabase-pr${{ env.PR_ID }}" >> $GITHUB_OUTPUT

  create_supabase:
    needs: prepare
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.TEST_SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.TEST_SUPABASE_PROJECT_ID }}

    steps:
    - name: 📥 Récupération du code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: ${{ env.BRANCH }}

    - name: 🛠️ Installation de la CLI Supabase
      uses: supabase/setup-cli@b60b5899c73b63a2d2d651b1e90db8d4c9392f51
      with:
        version: latest

    - name: 🪆 Creation de la branche Supabase
      run: |
       supabase branches create --size large ${{ needs.prepare.outputs.SUPABASE_REVIEW_APP_NAME }}

    # La configuration de chaque nouvelle branche reprend celle par défaut et non celle du projet parent.
    # Le fichier supabase/config.toml est le seul moyen documenté par Supabase
    # pour mettre à jour la configuration d'un projet.
    # https://github.com/orgs/supabase/discussions/3765
    # https://supabase.com/docs/reference/cli/supabase-config-push
    # APP_URL : Supabase est le SSO de Nuxt2. APP_URL est l'URL de redirection après la connexion par lien magique.
    # Configurée dans supabase/config.toml et dans l'interface : Supabase > Authorization > URL configuration.
    - name: 🤹‍♀️ Mise à jour de la configuration de Supabase
      continue-on-error: true
      shell: bash
      run: |
        until supabase branches get ${{ needs.prepare.outputs.SUPABASE_REVIEW_APP_NAME }} -o env | grep --quiet "SUPABASE_URL" &> /dev/null
        do
          echo "Attendons que la base Supabase soit prête pendant encore 20 secondes."
          sleep 20
        done

        DB_SECRETS=$(supabase branches get ${{ needs.prepare.outputs.SUPABASE_REVIEW_APP_NAME }} -o json)
        SUPABASE_BRANCH_ID=$(echo $DB_SECRETS | jq -r '.SUPABASE_URL' | sed --expression 's/\(https:\/\/\|\.supabase\.co\)//g')

        APP_URL="${{ needs.prepare.outputs.DJANGO_URL }}" supabase config push --project-ref "${SUPABASE_BRANCH_ID}" --yes

  create_nuxt3:
    needs: [prepare, create_supabase]
    runs-on: ubuntu-latest
    env:
      NUXT3_REPO_HTTPS: https://github.com/betagouv/docurba-nuxt3/
      NUXT3_BRANCH: main

    steps:
    - name: 🛠️ Installation de la CLI Scalingo
      uses: scalingo-community/setup-scalingo@87fe86eedc708ffb9d232c756b21f6a5784f6c8a # v0.1.1
      with:
        #  Jeton personnel de Céline Martinet Sanchez.
        api_token: ${{ secrets.SCALINGO_API_TOKEN }}
        region: 'osc-fr1'

    - name: 🛠️ Installation de la CLI Supabase
      uses: supabase/setup-cli@b60b5899c73b63a2d2d651b1e90db8d4c9392f51
      with:
        version: latest

    - name: 🛠️ Récupération des informations de BDD
      id: db
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.TEST_SUPABASE_ACCESS_TOKEN }}
        SUPABASE_PROJECT_ID: ${{ secrets.TEST_SUPABASE_PROJECT_ID }}
      run: |
        DB_SECRETS=$(supabase branches get ${{ needs.prepare.outputs.SUPABASE_REVIEW_APP_NAME }} -o json)

        SUPABASE_URL=$(echo $DB_SECRETS | jq -r '.SUPABASE_URL')
        echo "::add-mask::$SUPABASE_URL"
        echo "SUPABASE_URL=$SUPABASE_URL" >> "$GITHUB_OUTPUT"

        SUPABASE_SERVICE_ROLE_KEY=$(echo $DB_SECRETS | jq -r '.SUPABASE_SERVICE_ROLE_KEY')
        echo "::add-mask::$SUPABASE_SERVICE_ROLE_KEY"
        echo "SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY" >> "$GITHUB_OUTPUT"

    - name: Vérification de l'existence de l'application
      id: exists
      run: |
        if scalingo apps-info --app ${{ needs.prepare.outputs.NUXT_3_REVIEW_APP_NAME }} &> /dev/null
        then
          echo "APP_EXISTS=1" >> "$GITHUB_OUTPUT"
        else
          echo "APP_EXISTS=0" >> "$GITHUB_OUTPUT"
        fi

    - name: Création de l'application
      if: steps.exists.outputs.APP_EXISTS == '0'
      run: |
        # Il n'est pas possible de créer une recette jetable pour Nuxt3 car chaque recette jetable
        # s'appuie sur une branche Git différente de celle utilisée pour le dépôt parent.
        scalingo create "${{ needs.prepare.outputs.NUXT_3_REVIEW_APP_NAME }}"
        scalingo --app "${{ needs.prepare.outputs.NUXT_3_REVIEW_APP_NAME }}" integration-link-create --branch "${{ env.NUXT3_BRANCH }}" "${{ env.NUXT3_REPO_HTTPS }}"
        echo "Utilisation de la branche ${{ env.NUXT3_BRANCH }}."
        echo "Pour déployer une autre branche, vous pouvez modifier ce script ou utiliser l'interface graphique."

    - name: Mise à jour des variables d'environnement
      run: |
        scalingo --app ${{ needs.prepare.outputs.NUXT_3_REVIEW_APP_NAME }} env-set \
        SUPABASE_URL="${{ steps.db.outputs.SUPABASE_URL }}" \
        SUPABASE_ADMIN_KEY="${{ steps.db.outputs.SUPABASE_SERVICE_ROLE_KEY }}" \
        NODE_OPTIONS="--max-old-space-size=4096"

    - name: Déploiement de l'application
      run: scalingo --app "${{ needs.prepare.outputs.NUXT_3_REVIEW_APP_NAME }}" integration-link-manual-deploy main


  create_nuxt2:
    needs: [prepare, create_supabase]
    runs-on: ubuntu-latest
    env:
      SCALINGO_NUXT_APP_NAME: docurba-nuxt-demo

    steps:
    - name: 🛠️ Installation de la CLI Scalingo
      uses: scalingo-community/setup-scalingo@87fe86eedc708ffb9d232c756b21f6a5784f6c8a # v0.1.1
      with:
        #  Jeton personnel de Céline Martinet Sanchez.
        api_token: ${{ secrets.SCALINGO_API_TOKEN }}
        region: 'osc-fr1'

    - name: 🛠️ Installation de la CLI Supabase
      uses: supabase/setup-cli@b60b5899c73b63a2d2d651b1e90db8d4c9392f51
      with:
        version: latest

    - name: 🛠️ Récupération des informations de BDD
      id: db
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.TEST_SUPABASE_ACCESS_TOKEN }}
        SUPABASE_PROJECT_ID: ${{ secrets.TEST_SUPABASE_PROJECT_ID }}
      run: |
        DB_SECRETS=$(supabase branches get ${{ needs.prepare.outputs.SUPABASE_REVIEW_APP_NAME }} -o json)

        SUPABASE_URL=$(echo $DB_SECRETS | jq -r '.SUPABASE_URL')
        echo "::add-mask::$SUPABASE_URL"
        echo "SUPABASE_URL=$SUPABASE_URL" >> "$GITHUB_OUTPUT"

        SUPABASE_SERVICE_ROLE_KEY=$(echo $DB_SECRETS | jq -r '.SUPABASE_SERVICE_ROLE_KEY')
        echo "::add-mask::$SUPABASE_SERVICE_ROLE_KEY"
        echo "SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY" >> "$GITHUB_OUTPUT"

        SUPABASE_ANON_KEY=$(echo $DB_SECRETS | jq -r '.SUPABASE_ANON_KEY')
        echo "::add-mask::$SUPABASE_ANON_KEY"
        echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> "$GITHUB_OUTPUT"

    - name: Vérification de l'existence de l'application
      id: exists
      run: |
        if scalingo apps-info --app ${{ needs.prepare.outputs.NUXT_2_REVIEW_APP_NAME }} &> /dev/null
        then
          echo "APP_EXISTS=1" >> "$GITHUB_OUTPUT"
        else
          echo "APP_EXISTS=0" >> "$GITHUB_OUTPUT"
        fi

    - name: Création de l'application
      if: steps.exists.outputs.APP_EXISTS == '0'
      run: |
        # Le nom est créé par Scalingo.
        # Création d'une recette jetable.
        scalingo --app ${{ env.SCALINGO_NUXT_APP_NAME }} integration-link-manual-review-app ${{ env.PR_ID }}
        # Mise à jour de la configuration.
        scalingo --app "${{ needs.prepare.outputs.NUXT_2_REVIEW_APP_NAME }}" integration-link-update --auto-deploy --branch "${{ env.BRANCH }}" --destroy-on-close

    - name: Mise à jour des variables d'environnement
      run: |
        scalingo --app "${{ needs.prepare.outputs.NUXT_2_REVIEW_APP_NAME }}" env-set \
        SUPABASE_URL="${{ steps.db.outputs.SUPABASE_URL }}" \
        SUPABASE_ADMIN_KEY="${{ steps.db.outputs.SUPABASE_SERVICE_ROLE_KEY }}" \
        SUPABASE_ANON_KEY="${{ steps.db.outputs.SUPABASE_ANON_KEY }}" \
        NUXT3_API_URL="${{ needs.prepare.outputs.NUXT_3_URL }}" \
        APP_URL="${{ needs.prepare.outputs.DJANGO_URL }}" \
        DJANGO_API_BASE_URL="${{ needs.prepare.outputs.DJANGO_URL }}/api-internes" \
        USER_ENVIRONMENT="review_app"

    - name: Déploiement de l'application
      run: scalingo --app "${{ needs.prepare.outputs.NUXT_2_REVIEW_APP_NAME }}" integration-link-manual-deploy "${{ env.BRANCH }}"  &> /dev/null

    - name: Démarrage de l'application
      run: scalingo --app "${{ needs.prepare.outputs.NUXT_2_REVIEW_APP_NAME }}" scale web:1:M

    - name: Attente du démarrage réussi de l'application
      run: |
        until scalingo apps | grep "${{ needs.prepare.outputs.NUXT_2_REVIEW_APP_NAME }}" | grep --quiet 'running' &> /dev/null
        do
          echo "En attente de l'application Nuxt."
          sleep 10s
        done


  create_django:
    needs: [prepare, create_supabase]
    runs-on: ubuntu-latest
    env:
      SCALINGO_DJANGO_APP_NAME: docurba-django-demo

    steps:
    - name: 📥 Récupération du code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: ${{ env.BRANCH }}

    - name: 🛠️ Installation de la CLI Scalingo
      uses: scalingo-community/setup-scalingo@87fe86eedc708ffb9d232c756b21f6a5784f6c8a # v0.1.1
      with:
        #  Jeton personnel de Céline Martinet Sanchez.
        api_token: ${{ secrets.SCALINGO_API_TOKEN }}
        region: 'osc-fr1'

    - name: 🛠️ Installation de Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version-file: django/.python-version

    - name: 🛠️ Installation de la CLI Supabase
      uses: supabase/setup-cli@b60b5899c73b63a2d2d651b1e90db8d4c9392f51
      with:
        version: latest

    - name: 🛠️ Récupération des informations de BDD
      id: db
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.TEST_SUPABASE_ACCESS_TOKEN }}
        SUPABASE_PROJECT_ID: ${{ secrets.TEST_SUPABASE_PROJECT_ID }}
      run: |
        DB_SECRETS=$(supabase branches get ${{ needs.prepare.outputs.SUPABASE_REVIEW_APP_NAME }} -o json)

        POSTGRES_URL=$(echo $DB_SECRETS | jq -r '.POSTGRES_URL')
        echo "::add-mask::$POSTGRES_URL"
        echo "POSTGRES_URL=$POSTGRES_URL" >> "$GITHUB_OUTPUT"

    - name: Vérification de l'existence de l'application
      id: exists
      run: |
        if scalingo apps-info --app ${{ needs.prepare.outputs.DJANGO_REVIEW_APP_NAME }} &> /dev/null
        then
          echo "APP_EXISTS=1" >> "$GITHUB_OUTPUT"
        else
          echo "APP_EXISTS=0" >> "$GITHUB_OUTPUT"
        fi

    - name: Création de l'application
      if: steps.exists.outputs.APP_EXISTS == '0'
      run: |
        # Le nom est créé par Scalingo.
        # Création d'une recette jetable.
        scalingo --app ${{ env.SCALINGO_DJANGO_APP_NAME }} integration-link-manual-review-app ${{ env.PR_ID }}
        # Mise à jour de la configuration.
        scalingo --app "${{ needs.prepare.outputs.DJANGO_REVIEW_APP_NAME }}" integration-link-update --auto-deploy --branch "${{ env.BRANCH }}" --destroy-on-close

    - name: Mise à jour des variables d'environnement
      run: |
        # La longueur de la clé secrète doit être supérieure à 50 caractères,
        # or le générateur de secret de Scalingo génère une clé de 32 caractères.
        # Selon le support, il n'est pas possible d'en spécifier la longueur dans scalingo.json.
        django_secret_key=$(python -c "import secrets; print(secrets.token_hex(60))")
        echo "::add-mask::${django_secret_key}";
        scalingo --app "${{ needs.prepare.outputs.DJANGO_REVIEW_APP_NAME }}" env-set \
        UPSTREAM_NUXT="${{ needs.prepare.outputs.NUXT_2_URL }}" \
        DATABASE_URL="${{ steps.db.outputs.POSTGRES_URL }}" \
        NUXT3_API_URL="${{ needs.prepare.outputs.NUXT_3_URL }}" \
        SECRET_KEY="${django_secret_key}"

    - name: Déploiement de l'application
      run: scalingo --app "${{ needs.prepare.outputs.DJANGO_REVIEW_APP_NAME }}" integration-link-manual-deploy "${{ env.BRANCH }}" &> /dev/null

    - name: Démarrage de l'application
      run: scalingo --app "${{ needs.prepare.outputs.DJANGO_REVIEW_APP_NAME }}" scale web:1:M

    - name: Attente du démarrage réussi de l'application
      run: |
        until scalingo apps | grep "${{ needs.prepare.outputs.DJANGO_REVIEW_APP_NAME }}" | grep --quiet 'running' &> /dev/null
        do
          echo "En attente de l'application Django pendant 10 secondes."
          sleep 10s
        done


  comment_pr:
    needs: [prepare, create_supabase, create_nuxt3, create_nuxt2, create_django]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - name: 🍻 Ajout du lien en commentaire de la PR
      uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
      with:
        message: |-
          🥁 La recette jetable est prête ! [👉 Je veux tester cette PR !](${{ needs.prepare.outputs.DJANGO_URL }})
          Lien vers Nuxt3 pour modifier le déclencheur : [${{ needs.prepare.outputs.NUXT_3_URL }}](${{ needs.prepare.outputs.NUXT_3_URL }}).
          Attention, les données ne sont pas encore importées. Revenez quand l'action GitHub sera terminée.

  restore_and_migrate:
    needs: [prepare, comment_pr]
    runs-on: ubuntu-latest
    steps:
    - name: 🛠️ Installation de la CLI Scalingo
      uses: scalingo-community/setup-scalingo@87fe86eedc708ffb9d232c756b21f6a5784f6c8a # v0.1.1
      with:
        #  Jeton personnel de Céline Martinet Sanchez.
        api_token: ${{ secrets.SCALINGO_API_TOKEN }}
        region: 'osc-fr1'

    - name: 🔂 Génération des données
      run: scalingo --app "${{ needs.prepare.outputs.DJANGO_REVIEW_APP_NAME }}" run './scripts/restore_database.sh ${DATABASE_URL}' &> /dev/null

    - name: ⏩ Lancement des migrations et mise à jour du déclencheur utilisant Nuxt3
      run: |
        # La connexion PG doit être libérée avant de pouvoir passer les migrations
        # mais on ne sait jamais combien de temps Supabase met à le faire.
        sleep 5m
        scalingo --app "${{ needs.prepare.outputs.DJANGO_REVIEW_APP_NAME }}" run 'django-admin update_nuxt3_trigger && django-admin migrate'
