name: Sudocuh import
on:
  schedule:
    - cron: '10 18 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - env:
          PGPASSWORD: ${{ secrets.DEV_SUPABASE_PASSWORD }}
          DEV_SUPABASE_USER: ${{ secrets.DEV_SUPABASE_USER }}
          DEV_SUPABASE_ADMIN_KEY: ${{ secrets.DEV_SUPABASE_ADMIN_KEY }}
          DEV_SUPABASE_PASSWORD: ${{ secrets.DEV_SUPABASE_PASSWORD }}
          PROD_SUPABASE_USER: ${{ secrets.PROD_SUPABASE_USER }}
          PROD_SUPABASE_ADMIN_KEY: ${{ secrets.PROD_SUPABASE_ADMIN_KEY }}
          PROD_SUPABASE_PASSWORD: ${{ secrets.PROD_SUPABASE_PASSWORD }}
        run: npm run daily_dump

      - uses: actions/upload-artifact@v4
        with:
          path: daily_dump/output
